# Copyright (C) 2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-brook-server
LUCI_TITLE:=LuCI support for Brook Server
LUCI_DEPENDS:=+brook 
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=1-20200101

include $(TOPDIR)/feeds/luci/luci.mk 

# call BuildPackage - OpenWrt buildroot signature


