#!/bin/sh

[ "$ACTION" = "ifup" ] && {
	DK_MACVLANS=$(docker network ls -qf driver=macvlan)
	for DK_NETWORK_ID in ${DK_MACVLANS}
	do
		INTERFACE=$(docker network inspect "$DK_NETWORK_ID" --format '{{json .Options.parent}}' | sed -e 's/^"//' -e 's/"$//')
		[ "$INTERFACE" = "$DEVICE" ] && {
			echo "$DK_NETWORK_ID" >/tmp/dockerman
			echo "$INTERFACE" >>/tmp/dockerman
			DK_NETWORK_NAME=$(docker network inspect "$DK_NETWORK_ID" --format '{{json .Name}}' | sed -e 's/^"//' -e 's/"$//')
			ip link add link "$INTERFACE" "docker_$DK_NETWORK_NAME" type macvlan mode bridge >/dev/null 2>&1
			ip link set "docker_$DK_NETWORK_NAME" up >/dev/null 2>&1
		}
	done
}
