include $(TOPDIR)/rules.mk

LUCI_TITLE:=NJIT 802.1X Client for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for njit8021xclient.
LUCI_DEPENDS:=+njit8021xclient
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-njitclient
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
