#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@unblockneteasemusic-go[-1]
	add ucitrack unblockneteasemusic-go
	set ucitrack.@unblockneteasemusic-go[-1].init=unblockneteasemusic-go
	commit ucitrack
	delete firewall.unblockneteasemusic_go
	set firewall.unblockneteasemusic_go=include
	set firewall.unblockneteasemusic_go.type=script
	set firewall.unblockneteasemusic_go.path=/var/etc/unblockneteasemusic-go.include
	set firewall.unblockneteasemusic_go.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
