#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start() {
	rfc=4096
	threads="$(grep -c "processor" "/proc/cpuinfo")"

	sysctl -w net.core.rps_sock_flow_entries="$(( rfc * threads ))"

	for fileRps in /sys/class/net/eth*/queues/rx-*/rps_cpus
	do
		echo "$threads" > "$fileRps"
	done

	for fileRfc in /sys/class/net/eth*/queues/rx-*/rps_flow_cnt
	do
		echo "$rfc" > "$fileRfc"
	done

	uci set network.@globals[0].packet_steering="1"
	uci commit network

	for i in $(ip address | grep -E 'eth[0-9]+' | awk -F ': ' '{print $2}' | xargs)
	do
		{
			ethtool -K "$i" rx-checksum on
			ethtool -K "$i" tx-checksum-ip-generic on || {
				ethtool -K "$i" tx-checksum-ipv4 on
				ethtool -K "$i" tx-checksum-ipv6 on
			}
			ethtool -K "$i" tx-scatter-gather on
			ethtool -K "$i" gso on
			ethtool -K "$i" tso on
			ethtool -K "$i" ufo on
		}
	done

	[ ! -f '/etc/rpcd_10_system.js' ] || \
		mv -f '/etc/rpcd_10_system.js' '/www/luci-static/resources/view/status/include/10_system.js'
	[ ! -f '/etc/rpcd_luci' ] || \
		{ mv -f '/etc/rpcd_luci' '/usr/libexec/rpcd/luci'; rpcd_restart=1; }
	[ ! -f '/etc/rpcd_luci-mod-status.json' ] || \
		{ mv -f '/etc/rpcd_luci-mod-status.json' '/usr/share/rpcd/acl.d/luci-mod-status.json'; rpcd_restart=1; }
	[ -z "$rpcd_restart" ] || /etc/init.d/rpcd restart
} >"/dev/null" 2>&1
