#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	enable=$(uci get serverchan.serverchan.serverchan_enable)
	if [ $enable -eq 1 ]; then	
		/usr/bin/serverchan/serverchan &
		echo "serverchan is starting now ..."
	else
		/usr/bin/serverchan/serverchan crontab
		echo "serverchan is not enable, detect crontab and exit ..."
		stop
	fi
}

stop() {
	kill -9 `pgrep -f "/usr/bin/serverchan/serverchan"`  2>/dev/null
	echo "serverchan exit ..."
}

restart(){
	stop
	sleep 1
	start
} 
