#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set uhttpd.main.script_timeout="600"
	commit uhttpd
	delete ucitrack.@dockerd[-1]
	add ucitrack dockerd
	set ucitrack.@dockerd[-1].init=dockerd
	commit ucitrack
EOF
/etc/init.d/dockerd enable >/dev/null 2>&1
/etc/init.d/uhttpd restart >/dev/null 2>&1
rm -fr /tmp/luci-indexcache /tmp/luci-modulecache >/dev/null 2>&1
exit 0
