#!/bin/sh

cpu_cores="$(cat "/proc/cpuinfo" | grep "processor" | wc -l || echo -n "1")"
cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq) / 1000)MHz"
sys_temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"

echo -n "ARMv8 Processor x ${cpu_cores} (${cpu_freq}, ${sys_temp})"
