#!/bin/sh /etc/rc.common
# Copyright (C) 2015 By Wind

START=90
STOP=90

start() {
	config_load baidupcs
	enabled=$(uci get baidupcs.config.enabled)
	port=$(uci get baidupcs.config.port)
	path=$(uci get baidupcs.config.path)
	
	[ "$enabled" == "1" ] || return

	if [ ! -f "$path/baidupcs" ];then
		mkdir -p $path
		wget -O $path/baidupcs https://mirror.router.ctcgfw.generalcdn.top/download/mipsle/baidupcs-go && cd $path && ./baidupcs web --port $port --access >/dev/null 2>&1 &
	else
		$path/baidupcs web --port $port --access >/dev/null 2>&1 &
	fi
}

stop() {
	killall baidupcs >/dev/null 2>&1 &
}
