#!/bin/sh /etc/rc.common
# Copyright (C) 2015 By Wind

START=90
STOP=90

start() {
	config_load baidupcs
	enabled=$(uci get baidupcs.config.enabled)
	port=$(uci get baidupcs.config.port)
	path=$(uci get baidupcs.config.path)
	
	[ "$enabled" == "1" ] || return

	if [ ! -f "$path/baidupcs" ];then
		wget -O $path/baidupcs https://openwrt-cdn.netlify.com/download/bin/mipsle/baidupcs-go && cd $path && ./baidupcs web --port $port --access >/dev/null 2>/dev/null &
	else
		$path/baidupcs web --port $port --access >/dev/null 2>/dev/null &
	fi
}

stop() {
	killall baidupcs >/dev/null 2>/dev/null &
}