//[File]            : wf_wtblon_top.h
//[Revision time]   : Wed Dec 16 10:24:13 2020
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2020 Mediatek Incorportion. All rights reserved.

#ifndef __WF_WTBLON_TOP_REGS_H__
#define __WF_WTBLON_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     WF_WTBLON_TOP CR Definitions                     
//
//****************************************************************************

#define WF_WTBLON_TOP_BASE                                     0x820D4000

#define WF_WTBLON_TOP_RVCDAR0_ADDR                             (WF_WTBLON_TOP_BASE + 0x0000) // 4000
#define WF_WTBLON_TOP_RVCDAR1_ADDR                             (WF_WTBLON_TOP_BASE + 0x0004) // 4004
#define WF_WTBLON_TOP_RVCDAR2_ADDR                             (WF_WTBLON_TOP_BASE + 0x0008) // 4008
#define WF_WTBLON_TOP_RVCDAR3_ADDR                             (WF_WTBLON_TOP_BASE + 0x000C) // 400C
#define WF_WTBLON_TOP_RVCDAR4_ADDR                             (WF_WTBLON_TOP_BASE + 0x0010) // 4010
#define WF_WTBLON_TOP_RVCDAR5_ADDR                             (WF_WTBLON_TOP_BASE + 0x0014) // 4014
#define WF_WTBLON_TOP_RVCDAR6_ADDR                             (WF_WTBLON_TOP_BASE + 0x0018) // 4018
#define WF_WTBLON_TOP_RVCDAR7_ADDR                             (WF_WTBLON_TOP_BASE + 0x001C) // 401C
#define WF_WTBLON_TOP_RVCDAR8_ADDR                             (WF_WTBLON_TOP_BASE + 0x0020) // 4020
#define WF_WTBLON_TOP_RVCDAR9_ADDR                             (WF_WTBLON_TOP_BASE + 0x0024) // 4024
#define WF_WTBLON_TOP_RVCDAR10_ADDR                            (WF_WTBLON_TOP_BASE + 0x0028) // 4028
#define WF_WTBLON_TOP_RVCDAR11_ADDR                            (WF_WTBLON_TOP_BASE + 0x002C) // 402C
#define WF_WTBLON_TOP_RVCDAR12_ADDR                            (WF_WTBLON_TOP_BASE + 0x0030) // 4030
#define WF_WTBLON_TOP_RVCDAR13_ADDR                            (WF_WTBLON_TOP_BASE + 0x0034) // 4034
#define WF_WTBLON_TOP_RVCDAR14_ADDR                            (WF_WTBLON_TOP_BASE + 0x0038) // 4038
#define WF_WTBLON_TOP_RVCDAR15_ADDR                            (WF_WTBLON_TOP_BASE + 0x003C) // 403C
#define WF_WTBLON_TOP_RVCDAR16e_ADDR                           (WF_WTBLON_TOP_BASE + 0x0040) // 4040
#define WF_WTBLON_TOP_PSCDAR0_ADDR                             (WF_WTBLON_TOP_BASE + 0x0080) // 4080
#define WF_WTBLON_TOP_PSCDAR1_ADDR                             (WF_WTBLON_TOP_BASE + 0x0084) // 4084
#define WF_WTBLON_TOP_PSCDAR2_ADDR                             (WF_WTBLON_TOP_BASE + 0x0088) // 4088
#define WF_WTBLON_TOP_PSCDAR3_ADDR                             (WF_WTBLON_TOP_BASE + 0x008C) // 408C
#define WF_WTBLON_TOP_PSCDAR4_ADDR                             (WF_WTBLON_TOP_BASE + 0x0090) // 4090
#define WF_WTBLON_TOP_PSCDAR5_ADDR                             (WF_WTBLON_TOP_BASE + 0x0094) // 4094
#define WF_WTBLON_TOP_PSCDAR6_ADDR                             (WF_WTBLON_TOP_BASE + 0x0098) // 4098
#define WF_WTBLON_TOP_PSCDAR7_ADDR                             (WF_WTBLON_TOP_BASE + 0x009C) // 409C
#define WF_WTBLON_TOP_PSCDAR8_ADDR                             (WF_WTBLON_TOP_BASE + 0x00A0) // 40A0
#define WF_WTBLON_TOP_PSCDAR9_ADDR                             (WF_WTBLON_TOP_BASE + 0x00A4) // 40A4
#define WF_WTBLON_TOP_PSCDAR10_ADDR                            (WF_WTBLON_TOP_BASE + 0x00A8) // 40A8
#define WF_WTBLON_TOP_PSCDAR11_ADDR                            (WF_WTBLON_TOP_BASE + 0x00AC) // 40AC
#define WF_WTBLON_TOP_PSCDAR12_ADDR                            (WF_WTBLON_TOP_BASE + 0x00B0) // 40B0
#define WF_WTBLON_TOP_PSCDAR13_ADDR                            (WF_WTBLON_TOP_BASE + 0x00B4) // 40B4
#define WF_WTBLON_TOP_PSCDAR14_ADDR                            (WF_WTBLON_TOP_BASE + 0x00B8) // 40B8
#define WF_WTBLON_TOP_PSCDAR15_ADDR                            (WF_WTBLON_TOP_BASE + 0x00BC) // 40BC
#define WF_WTBLON_TOP_PSCDAR16e_ADDR                           (WF_WTBLON_TOP_BASE + 0x00C0) // 40C0
#define WF_WTBLON_TOP_TCGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0180) // 4180
#define WF_WTBLON_TOP_TCGSBR1_ADDR                             (WF_WTBLON_TOP_BASE + 0x0184) // 4184
#define WF_WTBLON_TOP_TCGSBRe_ADDR                             (WF_WTBLON_TOP_BASE + 0x0188) // 4188
#define WF_WTBLON_TOP_ACGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0190) // 4190
#define WF_WTBLON_TOP_ACGSBR1_ADDR                             (WF_WTBLON_TOP_BASE + 0x0194) // 4194
#define WF_WTBLON_TOP_ACGSBRe_ADDR                             (WF_WTBLON_TOP_BASE + 0x0198) // 4198
#define WF_WTBLON_TOP_RCGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x01A0) // 41A0
#define WF_WTBLON_TOP_RSCR_ADDR                                (WF_WTBLON_TOP_BASE + 0x01B4) // 41B4
#define WF_WTBLON_TOP_WDUCR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0200) // 4200
#define WF_WTBLON_TOP_RICR0_ADDR                               (WF_WTBLON_TOP_BASE + 0x0210) // 4210
#define WF_WTBLON_TOP_RICR1_ADDR                               (WF_WTBLON_TOP_BASE + 0x0214) // 4214
#define WF_WTBLON_TOP_RIUCR0_ADDR                              (WF_WTBLON_TOP_BASE + 0x0220) // 4220
#define WF_WTBLON_TOP_RIUCR1_ADDR                              (WF_WTBLON_TOP_BASE + 0x0224) // 4224
#define WF_WTBLON_TOP_RIUCR2_ADDR                              (WF_WTBLON_TOP_BASE + 0x0228) // 4228
#define WF_WTBLON_TOP_RIUCR3_ADDR                              (WF_WTBLON_TOP_BASE + 0x022C) // 422C
#define WF_WTBLON_TOP_WIUCR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0230) // 4230
#define WF_WTBLON_TOP_WMUDR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0234) // 4234
#define WF_WTBLON_TOP_WMUMR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0238) // 4238
#define WF_WTBLON_TOP_WTBLOR_ADDR                              (WF_WTBLON_TOP_BASE + 0x023C) // 423C
#define WF_WTBLON_TOP_MCR0_ADDR                                (WF_WTBLON_TOP_BASE + 0x0240) // 4240
#define WF_WTBLON_TOP_MCR1_ADDR                                (WF_WTBLON_TOP_BASE + 0x0244) // 4244
#define WF_WTBLON_TOP_MCR2_ADDR                                (WF_WTBLON_TOP_BASE + 0x0248) // 4248
#define WF_WTBLON_TOP_MBIST_0_ADDR                             (WF_WTBLON_TOP_BASE + 0x0300) // 4300
#define WF_WTBLON_TOP_MBIST_3_ADDR                             (WF_WTBLON_TOP_BASE + 0x030C) // 430C
#define WF_WTBLON_TOP_MBIST_4_ADDR                             (WF_WTBLON_TOP_BASE + 0x0310) // 4310
#define WF_WTBLON_TOP_MBIST_5_ADDR                             (WF_WTBLON_TOP_BASE + 0x0314) // 4314
#define WF_WTBLON_TOP_MBIST_6_ADDR                             (WF_WTBLON_TOP_BASE + 0x0318) // 4318
#define WF_WTBLON_TOP_MBIST_9_ADDR                             (WF_WTBLON_TOP_BASE + 0x0324) // 4324
#define WF_WTBLON_TOP_MBIST_10_ADDR                            (WF_WTBLON_TOP_BASE + 0x0328) // 4328
#define WF_WTBLON_TOP_MBIST_11_ADDR                            (WF_WTBLON_TOP_BASE + 0x032C) // 432C
#define WF_WTBLON_TOP_MBIST_12_ADDR                            (WF_WTBLON_TOP_BASE + 0x0330) // 4330
#define WF_WTBLON_TOP_MBIST_13_ADDR                            (WF_WTBLON_TOP_BASE + 0x0334) // 4334
#define WF_WTBLON_TOP_MBIST_14_ADDR                            (WF_WTBLON_TOP_BASE + 0x0338) // 4338
#define WF_WTBLON_TOP_DFR_ADDR                                 (WF_WTBLON_TOP_BASE + 0x0400) // 4400
#define WF_WTBLON_TOP_DBG_ADDR                                 (WF_WTBLON_TOP_BASE + 0x0404) // 4404
#define WF_WTBLON_TOP_DMY0_ADDR                                (WF_WTBLON_TOP_BASE + 0x04F0) // 44F0
#define WF_WTBLON_TOP_DMY1_ADDR                                (WF_WTBLON_TOP_BASE + 0x04F4) // 44F4




/* =====================================================================================

  ---RVCDAR0 (0x820D4000 + 0x0000)---

    RV_CACHE_0_7[7..0]           - (RW) Each bit is mapped to RV bit in bit 28@WTBL.
                                     SW uses this CR to read/write RV bit when Wi-Fi enters deep sleep mode.
                                     If wlan_idx > 32, RVCDAR+0x4*i store RV for wlan_idx 32*i ~32*(i+1)-1
                                     HW will update WTBL.RV automatically when this flag is updated.
    RV_CACHE_8_15[15..8]         - (RW) same as RV_CACHE_0_7
    RV_CACHE_16_31[31..16]       - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_16_31_ADDR              WF_WTBLON_TOP_RVCDAR0_ADDR
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_16_31_MASK              0xFFFF0000                // RV_CACHE_16_31[31..16]
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_16_31_SHFT              16
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_8_15_ADDR               WF_WTBLON_TOP_RVCDAR0_ADDR
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_8_15_MASK               0x0000FF00                // RV_CACHE_8_15[15..8]
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_8_15_SHFT               8
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_0_7_ADDR                WF_WTBLON_TOP_RVCDAR0_ADDR
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_0_7_MASK                0x000000FF                // RV_CACHE_0_7[7..0]
#define WF_WTBLON_TOP_RVCDAR0_RV_CACHE_0_7_SHFT                0

/* =====================================================================================

  ---RVCDAR1 (0x820D4000 + 0x0004)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR1_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR1_ADDR
#define WF_WTBLON_TOP_RVCDAR1_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR1_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR2 (0x820D4000 + 0x0008)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR2_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR2_ADDR
#define WF_WTBLON_TOP_RVCDAR2_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR2_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR3 (0x820D4000 + 0x000C)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR3_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR3_ADDR
#define WF_WTBLON_TOP_RVCDAR3_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR3_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR4 (0x820D4000 + 0x0010)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR4_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR4_ADDR
#define WF_WTBLON_TOP_RVCDAR4_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR4_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR5 (0x820D4000 + 0x0014)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR5_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR5_ADDR
#define WF_WTBLON_TOP_RVCDAR5_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR5_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR6 (0x820D4000 + 0x0018)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR6_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR6_ADDR
#define WF_WTBLON_TOP_RVCDAR6_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR6_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR7 (0x820D4000 + 0x001C)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR7_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR7_ADDR
#define WF_WTBLON_TOP_RVCDAR7_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR7_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR8 (0x820D4000 + 0x0020)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR8_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR8_ADDR
#define WF_WTBLON_TOP_RVCDAR8_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR8_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR9 (0x820D4000 + 0x0024)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR9_RV_CACHE_ADDR                    WF_WTBLON_TOP_RVCDAR9_ADDR
#define WF_WTBLON_TOP_RVCDAR9_RV_CACHE_MASK                    0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR9_RV_CACHE_SHFT                    0

/* =====================================================================================

  ---RVCDAR10 (0x820D4000 + 0x0028)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR10_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR10_ADDR
#define WF_WTBLON_TOP_RVCDAR10_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR10_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR11 (0x820D4000 + 0x002C)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR11_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR11_ADDR
#define WF_WTBLON_TOP_RVCDAR11_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR11_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR12 (0x820D4000 + 0x0030)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR12_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR12_ADDR
#define WF_WTBLON_TOP_RVCDAR12_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR12_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR13 (0x820D4000 + 0x0034)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR13_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR13_ADDR
#define WF_WTBLON_TOP_RVCDAR13_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR13_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR14 (0x820D4000 + 0x0038)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR14_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR14_ADDR
#define WF_WTBLON_TOP_RVCDAR14_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR14_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR15 (0x820D4000 + 0x003C)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR15_RV_CACHE_ADDR                   WF_WTBLON_TOP_RVCDAR15_ADDR
#define WF_WTBLON_TOP_RVCDAR15_RV_CACHE_MASK                   0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR15_RV_CACHE_SHFT                   0

/* =====================================================================================

  ---RVCDAR16e (0x820D4000 + 0x0040)---

    RV_CACHE[31..0]              - (RW) same as RV_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR16e_RV_CACHE_ADDR                  WF_WTBLON_TOP_RVCDAR16e_ADDR
#define WF_WTBLON_TOP_RVCDAR16e_RV_CACHE_MASK                  0xFFFFFFFF                // RV_CACHE[31..0]
#define WF_WTBLON_TOP_RVCDAR16e_RV_CACHE_SHFT                  0

/* =====================================================================================

  ---PSCDAR0 (0x820D4000 + 0x0080)---

    PS_CACHE_0_7[7..0]           - (RW) Each bit is mapped to PS INFO bit (calculate by WTBL).
                                     SW uses this CR to read/write PS INFO bit when Wi-Fi enters deep sleep mode.
                                     If wlan_idx > 32, PSCDAR+0x4*i store PS for wlan_idx 32*i ~32*(i+1)-1
    PS_CACHE_8_15[15..8]         - (RW) same as PS_CACHE_0_7
    PS_CACHE_16_31[31..16]       - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_16_31_ADDR              WF_WTBLON_TOP_PSCDAR0_ADDR
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_16_31_MASK              0xFFFF0000                // PS_CACHE_16_31[31..16]
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_16_31_SHFT              16
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_8_15_ADDR               WF_WTBLON_TOP_PSCDAR0_ADDR
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_8_15_MASK               0x0000FF00                // PS_CACHE_8_15[15..8]
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_8_15_SHFT               8
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_0_7_ADDR                WF_WTBLON_TOP_PSCDAR0_ADDR
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_0_7_MASK                0x000000FF                // PS_CACHE_0_7[7..0]
#define WF_WTBLON_TOP_PSCDAR0_PS_CACHE_0_7_SHFT                0

/* =====================================================================================

  ---PSCDAR1 (0x820D4000 + 0x0084)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR1_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR1_ADDR
#define WF_WTBLON_TOP_PSCDAR1_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR1_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR2 (0x820D4000 + 0x0088)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR2_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR2_ADDR
#define WF_WTBLON_TOP_PSCDAR2_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR2_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR3 (0x820D4000 + 0x008C)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR3_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR3_ADDR
#define WF_WTBLON_TOP_PSCDAR3_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR3_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR4 (0x820D4000 + 0x0090)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR4_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR4_ADDR
#define WF_WTBLON_TOP_PSCDAR4_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR4_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR5 (0x820D4000 + 0x0094)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR5_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR5_ADDR
#define WF_WTBLON_TOP_PSCDAR5_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR5_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR6 (0x820D4000 + 0x0098)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR6_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR6_ADDR
#define WF_WTBLON_TOP_PSCDAR6_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR6_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR7 (0x820D4000 + 0x009C)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR7_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR7_ADDR
#define WF_WTBLON_TOP_PSCDAR7_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR7_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR8 (0x820D4000 + 0x00A0)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR8_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR8_ADDR
#define WF_WTBLON_TOP_PSCDAR8_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR8_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR9 (0x820D4000 + 0x00A4)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR9_PS_CACHE_ADDR                    WF_WTBLON_TOP_PSCDAR9_ADDR
#define WF_WTBLON_TOP_PSCDAR9_PS_CACHE_MASK                    0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR9_PS_CACHE_SHFT                    0

/* =====================================================================================

  ---PSCDAR10 (0x820D4000 + 0x00A8)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR10_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR10_ADDR
#define WF_WTBLON_TOP_PSCDAR10_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR10_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR11 (0x820D4000 + 0x00AC)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR11_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR11_ADDR
#define WF_WTBLON_TOP_PSCDAR11_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR11_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR12 (0x820D4000 + 0x00B0)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR12_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR12_ADDR
#define WF_WTBLON_TOP_PSCDAR12_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR12_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR13 (0x820D4000 + 0x00B4)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR13_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR13_ADDR
#define WF_WTBLON_TOP_PSCDAR13_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR13_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR14 (0x820D4000 + 0x00B8)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR14_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR14_ADDR
#define WF_WTBLON_TOP_PSCDAR14_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR14_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR15 (0x820D4000 + 0x00BC)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR15_PS_CACHE_ADDR                   WF_WTBLON_TOP_PSCDAR15_ADDR
#define WF_WTBLON_TOP_PSCDAR15_PS_CACHE_MASK                   0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR15_PS_CACHE_SHFT                   0

/* =====================================================================================

  ---PSCDAR16e (0x820D4000 + 0x00C0)---

    PS_CACHE[31..0]              - (RW) same as PS_CACHE_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR16e_PS_CACHE_ADDR                  WF_WTBLON_TOP_PSCDAR16e_ADDR
#define WF_WTBLON_TOP_PSCDAR16e_PS_CACHE_MASK                  0xFFFFFFFF                // PS_CACHE[31..0]
#define WF_WTBLON_TOP_PSCDAR16e_PS_CACHE_SHFT                  0

/* =====================================================================================

  ---TCGSBR (0x820D4000 + 0x0180)---

    TX_CNT_STATUS_BITMAP_0_7[0]  - (RW) Group bitmap for TX count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.
    TX_CNT_STATUS_BITMAP_8_15[1] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_16_31[3..2] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_32_63[7..4] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_64_127[15..8] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_128_255[31..16] - (RW) same as TX_CNT_STATUS_BITMAP_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_128_255_ADDR WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_128_255_MASK 0xFFFF0000                // TX_CNT_STATUS_BITMAP_128_255[31..16]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_128_255_SHFT 16
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_ADDR  WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_MASK  0x0000FF00                // TX_CNT_STATUS_BITMAP_64_127[15..8]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_SHFT  8
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_ADDR   WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_MASK   0x000000F0                // TX_CNT_STATUS_BITMAP_32_63[7..4]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_SHFT   4
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_ADDR   WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_MASK   0x0000000C                // TX_CNT_STATUS_BITMAP_16_31[3..2]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_SHFT   2
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_ADDR    WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_MASK    0x00000002                // TX_CNT_STATUS_BITMAP_8_15[1]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_SHFT    1
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_ADDR     WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_MASK     0x00000001                // TX_CNT_STATUS_BITMAP_0_7[0]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_SHFT     0

/* =====================================================================================

  ---TCGSBR1 (0x820D4000 + 0x0184)---

    TX_CNT_STATUS_BITMAP_256_511[31..0] - (RW) Group bitmap for TX count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.

 =====================================================================================*/
#define WF_WTBLON_TOP_TCGSBR1_TX_CNT_STATUS_BITMAP_256_511_ADDR WF_WTBLON_TOP_TCGSBR1_ADDR
#define WF_WTBLON_TOP_TCGSBR1_TX_CNT_STATUS_BITMAP_256_511_MASK 0xFFFFFFFF                // TX_CNT_STATUS_BITMAP_256_511[31..0]
#define WF_WTBLON_TOP_TCGSBR1_TX_CNT_STATUS_BITMAP_256_511_SHFT 0

/* =====================================================================================

  ---TCGSBRe (0x820D4000 + 0x0188)---

    TX_CNT_STATUS_BITMAP_e0_7[0] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_e8_15[1] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_e16_31[3..2] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e16_31_ADDR WF_WTBLON_TOP_TCGSBRe_ADDR
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e16_31_MASK 0x0000000C                // TX_CNT_STATUS_BITMAP_e16_31[3..2]
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e16_31_SHFT 2
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e8_15_ADDR  WF_WTBLON_TOP_TCGSBRe_ADDR
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e8_15_MASK  0x00000002                // TX_CNT_STATUS_BITMAP_e8_15[1]
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e8_15_SHFT  1
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_ADDR   WF_WTBLON_TOP_TCGSBRe_ADDR
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_MASK   0x00000001                // TX_CNT_STATUS_BITMAP_e0_7[0]
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_SHFT   0

/* =====================================================================================

  ---ACGSBR (0x820D4000 + 0x0190)---

    ADM_CNT_STATUS_BITMAP_0_7[0] - (RW) Group bitmap for ADM count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.
    ADM_CNT_STATUS_BITMAP_8_15[1] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_16_31[3..2] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_32_63[7..4] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_64_127[15..8] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_128_255[31..16] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7

 =====================================================================================*/
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_128_255_ADDR WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_128_255_MASK 0xFFFF0000                // ADM_CNT_STATUS_BITMAP_128_255[31..16]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_128_255_SHFT 16
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_ADDR WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_MASK 0x0000FF00                // ADM_CNT_STATUS_BITMAP_64_127[15..8]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_SHFT 8
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_ADDR  WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_MASK  0x000000F0                // ADM_CNT_STATUS_BITMAP_32_63[7..4]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_SHFT  4
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_ADDR  WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_MASK  0x0000000C                // ADM_CNT_STATUS_BITMAP_16_31[3..2]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_SHFT  2
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_ADDR   WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_MASK   0x00000002                // ADM_CNT_STATUS_BITMAP_8_15[1]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_SHFT   1
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_ADDR    WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_MASK    0x00000001                // ADM_CNT_STATUS_BITMAP_0_7[0]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_SHFT    0

/* =====================================================================================

  ---ACGSBR1 (0x820D4000 + 0x0194)---

    ADM_CNT_STATUS_BITMAP_256_511[31..0] - (RW) Group bitmap for ADM count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.

 =====================================================================================*/
#define WF_WTBLON_TOP_ACGSBR1_ADM_CNT_STATUS_BITMAP_256_511_ADDR WF_WTBLON_TOP_ACGSBR1_ADDR
#define WF_WTBLON_TOP_ACGSBR1_ADM_CNT_STATUS_BITMAP_256_511_MASK 0xFFFFFFFF                // ADM_CNT_STATUS_BITMAP_256_511[31..0]
#define WF_WTBLON_TOP_ACGSBR1_ADM_CNT_STATUS_BITMAP_256_511_SHFT 0

/* =====================================================================================

  ---ACGSBRe (0x820D4000 + 0x0198)---

    ADM_CNT_STATUS_BITMAP_e0_7[0] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_e8_15[1] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_e16_31[3..2] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e16_31_ADDR WF_WTBLON_TOP_ACGSBRe_ADDR
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e16_31_MASK 0x0000000C                // ADM_CNT_STATUS_BITMAP_e16_31[3..2]
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e16_31_SHFT 2
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e8_15_ADDR WF_WTBLON_TOP_ACGSBRe_ADDR
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e8_15_MASK 0x00000002                // ADM_CNT_STATUS_BITMAP_e8_15[1]
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e8_15_SHFT 1
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_ADDR  WF_WTBLON_TOP_ACGSBRe_ADDR
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_MASK  0x00000001                // ADM_CNT_STATUS_BITMAP_e0_7[0]
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_SHFT  0

/* =====================================================================================

  ---RCGSBR (0x820D4000 + 0x01A0)---

    RATE_CHANGE_STATUS_BITMAP[31..0] - (RW) Group bitmap for rate change status
                                     Each bit is mapped to 8 entries in WLAN entry.
                                     For example,
                                     a = WTBL_NO/8.
                                     bit 0->WLAN entry a*n,
                                     bit 1->WLAN entry a*n+1,
                                     ...
                                     bit m->WLAN entry a*n+m (m <= a).
                                     SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.

 =====================================================================================*/
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_ADDR    WF_WTBLON_TOP_RCGSBR_ADDR
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_MASK    0xFFFFFFFF                // RATE_CHANGE_STATUS_BITMAP[31..0]
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_SHFT    0

/* =====================================================================================

  ---RSCR (0x820D4000 + 0x01B4)---

    WTBL_SU_SEARCH[0]            - (RW) WTBL search mode
    WTBL_PRECISE_MATCH[1]        - (RW) Precise match when checking peer address
                                     WTBL do NOT ignore individual/group bit in address check when comparing the peer address with A2
    WTBL_MISS_NOTIFY[2]          - (RW) WTBL miss indicator
                                     available in AP mode
    RESERVED3[30..3]             - (RO) Reserved bits
    WTBL_ACCESS_CONCURRENT[31]   - (RW) WTBL allows non-ID table access & ID table access in the same time to reduce the processing time

 =====================================================================================*/
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_ADDR         WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_MASK         0x80000000                // WTBL_ACCESS_CONCURRENT[31]
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_SHFT         31
#define WF_WTBLON_TOP_RSCR_WTBL_MISS_NOTIFY_ADDR               WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_MISS_NOTIFY_MASK               0x00000004                // WTBL_MISS_NOTIFY[2]
#define WF_WTBLON_TOP_RSCR_WTBL_MISS_NOTIFY_SHFT               2
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_ADDR             WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_MASK             0x00000002                // WTBL_PRECISE_MATCH[1]
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_SHFT             1
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_ADDR                 WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_MASK                 0x00000001                // WTBL_SU_SEARCH[0]
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_SHFT                 0

/* =====================================================================================

  ---WDUCR (0x820D4000 + 0x0200)---

    GROUP[2..0]                  - (RW) The selected group of wtbl
                                     128 entries for each group
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_WDUCR_GROUP_ADDR                         WF_WTBLON_TOP_WDUCR_ADDR
#define WF_WTBLON_TOP_WDUCR_GROUP_MASK                         0x00000007                // GROUP[2..0]
#define WF_WTBLON_TOP_WDUCR_GROUP_SHFT                         0

/* =====================================================================================

  ---RICR0 (0x820D4000 + 0x0210)---

    DW0_WTBL[31..0]              - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RXINFO_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_ADDR                      WF_WTBLON_TOP_RICR0_ADDR
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_MASK                      0xFFFFFFFF                // DW0_WTBL[31..0]
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_SHFT                      0

/* =====================================================================================

  ---RICR1 (0x820D4000 + 0x0214)---

    DW1_WTBL[31..0]              - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RXINFO_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_ADDR                      WF_WTBLON_TOP_RICR1_ADDR
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_MASK                      0xFFFFFFFF                // DW1_WTBL[31..0]
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_SHFT                      0

/* =====================================================================================

  ---RIUCR0 (0x820D4000 + 0x0220)---

    DW10_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR0_ADDR
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_MASK                    0xFFFFFFFF                // DW10_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR1 (0x820D4000 + 0x0224)---

    DW11_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR1_ADDR
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_MASK                    0xFFFFFFFF                // DW11_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR2 (0x820D4000 + 0x0228)---

    DW12_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR2_ADDR
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_MASK                    0xFFFFFFFF                // DW12_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR3 (0x820D4000 + 0x022C)---

    DW13_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR3_ADDR
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_MASK                    0xFFFFFFFF                // DW13_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_SHFT                    0

/* =====================================================================================

  ---WIUCR (0x820D4000 + 0x0230)---

    WLAN_IDX[9..0]               - (RW) Target for clearing or updating
    RESERVED10[10]               - (RO) Reserved bits
    RXINFO_UPDATE[11]            - (W1) Updates RX information according to the value of RICRn (n=0~1)
    ADM_CNT_CLEAR[12]            - (W1) Clear ADM counter to 0
    RATE_UPDATE[13]              - (W1) Updates rate information according to the value of RIUCRn (n=0~3) and clears rate_idx, mpdu_cnt
    TX_RATE_CNT_CLEAR[14]        - (W1) Clear TX rate/BW CNTs and CHK_PER to 0
    RX_CNT_CLEAR[15]             - (W1) Sets RCPI, RSSI, SNR to initial value.
    RTS_CNT_CLEAR[16]            - (W1) Clear RTS counter & RTS_FAIL_CNT_AC* to 0
    RETRY_CNT_CLEAR[17]          - (W1) Clear retry counter to 0
    RESERVED18[19..18]           - (RO) Reserved bits
    MASK_UPDATE[20]              - (W1) Mask Update
                                     WTBL loads target wlan_idx & dw and update the target field by WMUDR & WMUMR
    RESERVED21[23..21]           - (RO) Reserved bits
    DW[29..24]                   - (RW) Target double word
    RESERVED30[30]               - (RO) Reserved bits
    IU_BUSY[31]                  - (RO) Indirect update status
                                     HW will set up this bit when it is updating WTBL.

 =====================================================================================*/
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_ADDR                       WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_MASK                       0x80000000                // IU_BUSY[31]
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_SHFT                       31
#define WF_WTBLON_TOP_WIUCR_DW_ADDR                            WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_DW_MASK                            0x3F000000                // DW[29..24]
#define WF_WTBLON_TOP_WIUCR_DW_SHFT                            24
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_ADDR                   WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_MASK                   0x00100000                // MASK_UPDATE[20]
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_SHFT                   20
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_ADDR               WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_MASK               0x00020000                // RETRY_CNT_CLEAR[17]
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_SHFT               17
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_ADDR                 WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_MASK                 0x00010000                // RTS_CNT_CLEAR[16]
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_SHFT                 16
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_ADDR                  WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_MASK                  0x00008000                // RX_CNT_CLEAR[15]
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_SHFT                  15
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_ADDR             WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_MASK             0x00004000                // TX_RATE_CNT_CLEAR[14]
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_SHFT             14
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_ADDR                   WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_MASK                   0x00002000                // RATE_UPDATE[13]
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_SHFT                   13
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_ADDR                 WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_MASK                 0x00001000                // ADM_CNT_CLEAR[12]
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_SHFT                 12
#define WF_WTBLON_TOP_WIUCR_RXINFO_UPDATE_ADDR                 WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RXINFO_UPDATE_MASK                 0x00000800                // RXINFO_UPDATE[11]
#define WF_WTBLON_TOP_WIUCR_RXINFO_UPDATE_SHFT                 11
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_ADDR                      WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_MASK                      0x000003FF                // WLAN_IDX[9..0]
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_SHFT                      0

/* =====================================================================================

  ---WMUDR (0x820D4000 + 0x0234)---

    UPDATE_DATA[31..0]           - (RW) Data to update wlan entry

 =====================================================================================*/
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_ADDR                   WF_WTBLON_TOP_WMUDR_ADDR
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_MASK                   0xFFFFFFFF                // UPDATE_DATA[31..0]
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_SHFT                   0

/* =====================================================================================

  ---WMUMR (0x820D4000 + 0x0238)---

    UPDATE_MASK[31..0]           - (RW) Mask of data to update wlan entry

 =====================================================================================*/
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_ADDR                   WF_WTBLON_TOP_WMUMR_ADDR
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_MASK                   0xFFFFFFFF                // UPDATE_MASK[31..0]
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_SHFT                   0

/* =====================================================================================

  ---WTBLOR (0x820D4000 + 0x023C)---

    LOCK_WLAN_IDX[9..0]          - (RW) Target for locking
    RESERVED10[11..10]           - (RO) Reserved bits
    LOCK_RATE[12]                - (RW) Lock rate update
                                     Read this flag to know if it is locked or not.
    RESERVED13[19..13]           - (RO) Reserved bits
    LOCK_ADM_CNT[20]             - (RW) Lock admission control counter update
                                     Read this flag to know if it is locked or not.
    RESERVED21[23..21]           - (RO) Reserved bits
    LOCK_TX_CNT[24]              - (RW) Lock TX/RTS/retry counter update
                                     Read this flag to know if it is locked or not.
    RESERVED25[27..25]           - (RO) Reserved bits
    LOCK_RX_STAT_CNT[28]         - (RW) Lock RX counter update
                                     Read this flag to know if it is locked or not.
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_ADDR             WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_MASK             0x10000000                // LOCK_RX_STAT_CNT[28]
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_SHFT             28
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_ADDR                  WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_MASK                  0x01000000                // LOCK_TX_CNT[24]
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_SHFT                  24
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_ADDR                 WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_MASK                 0x00100000                // LOCK_ADM_CNT[20]
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_SHFT                 20
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_ADDR                    WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_MASK                    0x00001000                // LOCK_RATE[12]
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_SHFT                    12
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_ADDR                WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_MASK                0x000003FF                // LOCK_WLAN_IDX[9..0]
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_SHFT                0

/* =====================================================================================

  ---MCR0 (0x820D4000 + 0x0240)---

    MISS_CACHE_DW0[31..0]        - (RO) Miss Cache DW0
                                     When WTBL search miss is occurred, it records the oldest info for the missed STA.

 =====================================================================================*/
#define WF_WTBLON_TOP_MCR0_MISS_CACHE_DW0_ADDR                 WF_WTBLON_TOP_MCR0_ADDR
#define WF_WTBLON_TOP_MCR0_MISS_CACHE_DW0_MASK                 0xFFFFFFFF                // MISS_CACHE_DW0[31..0]
#define WF_WTBLON_TOP_MCR0_MISS_CACHE_DW0_SHFT                 0

/* =====================================================================================

  ---MCR1 (0x820D4000 + 0x0244)---

    MISS_CACHE_DW1[31..0]        - (RO) Miss Cache DW1
                                     When WTBL search miss is occurred, it records the oldest info for the missed STA.
                                     After reading this DW, WTBL pops up the last entry in Miss Cache

 =====================================================================================*/
#define WF_WTBLON_TOP_MCR1_MISS_CACHE_DW1_ADDR                 WF_WTBLON_TOP_MCR1_ADDR
#define WF_WTBLON_TOP_MCR1_MISS_CACHE_DW1_MASK                 0xFFFFFFFF                // MISS_CACHE_DW1[31..0]
#define WF_WTBLON_TOP_MCR1_MISS_CACHE_DW1_SHFT                 0

/* =====================================================================================

  ---MCR2 (0x820D4000 + 0x0248)---

    MISS_CACHE_LOSS_COUNT[7..0]  - (RO) # of loss event for WTBL search miss notifier
                                     This counter is increased when WTBL search miss is occurred but miss cache unable to push any info(full)
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MCR2_MISS_CACHE_LOSS_COUNT_ADDR          WF_WTBLON_TOP_MCR2_ADDR
#define WF_WTBLON_TOP_MCR2_MISS_CACHE_LOSS_COUNT_MASK          0x000000FF                // MISS_CACHE_LOSS_COUNT[7..0]
#define WF_WTBLON_TOP_MCR2_MISS_CACHE_LOSS_COUNT_SHFT          0

/* =====================================================================================

  ---MBIST_0 (0x820D4000 + 0x0300)---

    RESERVED0[2..0]              - (RO) Reserved bits
    MEM_USE_DEFAULT_DELSEL[3]    - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_ADDR      WF_WTBLON_TOP_MBIST_0_ADDR
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_MASK      0x00000008                // MEM_USE_DEFAULT_DELSEL[3]
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_SHFT      3

/* =====================================================================================

  ---MBIST_3 (0x820D4000 + 0x030C)---

    MEM_DELSEL_0[31..0]          - (RW)  xxx 

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_ADDR                WF_WTBLON_TOP_MBIST_3_ADDR
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_MASK                0xFFFFFFFF                // MEM_DELSEL_0[31..0]
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_SHFT                0

/* =====================================================================================

  ---MBIST_4 (0x820D4000 + 0x0310)---

    MEM_DELSEL_1[31..0]          - (RW)  xxx 

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_ADDR                WF_WTBLON_TOP_MBIST_4_ADDR
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_MASK                0xFFFFFFFF                // MEM_DELSEL_1[31..0]
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_SHFT                0

/* =====================================================================================

  ---MBIST_5 (0x820D4000 + 0x0314)---

    MEM_DELSEL_2[31..0]          - (RW)  xxx 

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_ADDR                WF_WTBLON_TOP_MBIST_5_ADDR
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_MASK                0xFFFFFFFF                // MEM_DELSEL_2[31..0]
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_SHFT                0

/* =====================================================================================

  ---MBIST_6 (0x820D4000 + 0x0318)---

    MBIST_FUSE[6..0]             - (RW)  xxx 
    RESERVED7[7]                 - (RO) Reserved bits
    MBIST_PRE_FUSE_0[14..8]      - (RO)  xxx 
    RESERVED15[23..15]           - (RO) Reserved bits
    MBIST_PRE_FUSE_1[30..24]     - (RO)  xxx 
    RESERVED31[31]               - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_1_ADDR            WF_WTBLON_TOP_MBIST_6_ADDR
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_1_MASK            0x7F000000                // MBIST_PRE_FUSE_1[30..24]
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_1_SHFT            24
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_0_ADDR            WF_WTBLON_TOP_MBIST_6_ADDR
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_0_MASK            0x00007F00                // MBIST_PRE_FUSE_0[14..8]
#define WF_WTBLON_TOP_MBIST_6_MBIST_PRE_FUSE_0_SHFT            8
#define WF_WTBLON_TOP_MBIST_6_MBIST_FUSE_ADDR                  WF_WTBLON_TOP_MBIST_6_ADDR
#define WF_WTBLON_TOP_MBIST_6_MBIST_FUSE_MASK                  0x0000007F                // MBIST_FUSE[6..0]
#define WF_WTBLON_TOP_MBIST_6_MBIST_FUSE_SHFT                  0

/* =====================================================================================

  ---MBIST_9 (0x820D4000 + 0x0324)---

    MBIST_RP_OK[26..0]           - (RO)  xxx 
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_9_MBIST_RP_OK_ADDR                 WF_WTBLON_TOP_MBIST_9_ADDR
#define WF_WTBLON_TOP_MBIST_9_MBIST_RP_OK_MASK                 0x07FFFFFF                // MBIST_RP_OK[26..0]
#define WF_WTBLON_TOP_MBIST_9_MBIST_RP_OK_SHFT                 0

/* =====================================================================================

  ---MBIST_10 (0x820D4000 + 0x0328)---

    MBIST_RP_FAIL[26..0]         - (RO)  xxx 
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_10_MBIST_RP_FAIL_ADDR              WF_WTBLON_TOP_MBIST_10_ADDR
#define WF_WTBLON_TOP_MBIST_10_MBIST_RP_FAIL_MASK              0x07FFFFFF                // MBIST_RP_FAIL[26..0]
#define WF_WTBLON_TOP_MBIST_10_MBIST_RP_FAIL_SHFT              0

/* =====================================================================================

  ---MBIST_11 (0x820D4000 + 0x032C)---

    MBIST_REG_FUSE_SEL[0]        - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_ADDR         WF_WTBLON_TOP_MBIST_11_ADDR
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_MASK         0x00000001                // MBIST_REG_FUSE_SEL[0]
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_SHFT         0

/* =====================================================================================

  ---MBIST_12 (0x820D4000 + 0x0330)---

    LMACON_MBIST_PREFUSE_0[15..0] - (RO)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_ADDR     WF_WTBLON_TOP_MBIST_12_ADDR
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_MASK     0x0000FFFF                // LMACON_MBIST_PREFUSE_0[15..0]
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_SHFT     0

/* =====================================================================================

  ---MBIST_13 (0x820D4000 + 0x0334)---

    LMACON_MBIST_PREFUSE_D_0[15..0] - (RO)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_ADDR   WF_WTBLON_TOP_MBIST_13_ADDR
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_MASK   0x0000FFFF                // LMACON_MBIST_PREFUSE_D_0[15..0]
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_SHFT   0

/* =====================================================================================

  ---MBIST_14 (0x820D4000 + 0x0338)---

    FUSE_LOAD_SEL[0]             - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_ADDR              WF_WTBLON_TOP_MBIST_14_ADDR
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_MASK              0x00000001                // FUSE_LOAD_SEL[0]
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_SHFT              0

/* =====================================================================================

  ---DFR (0x820D4000 + 0x0400)---

    SRAMIF_CS[7..0]              - (RO) SRAM interface FSM
    MUCOPIF_DEB[11..8]           - (RO) MUCOP interface debug
    MDPIF_DBG[15..12]            - (RO) MDP interface debug
    CTRIF_DBG[19..16]            - (RO) Counter Update interface debug
    RESERVED20[27..20]           - (RO) Reserved bits
    SIFIF_CS[30..28]             - (RO) SIF interface FSM
    RESERVED31[31]               - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_DFR_SIFIF_CS_ADDR                        WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SIFIF_CS_MASK                        0x70000000                // SIFIF_CS[30..28]
#define WF_WTBLON_TOP_DFR_SIFIF_CS_SHFT                        28
#define WF_WTBLON_TOP_DFR_CTRIF_DBG_ADDR                       WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_CTRIF_DBG_MASK                       0x000F0000                // CTRIF_DBG[19..16]
#define WF_WTBLON_TOP_DFR_CTRIF_DBG_SHFT                       16
#define WF_WTBLON_TOP_DFR_MDPIF_DBG_ADDR                       WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_MDPIF_DBG_MASK                       0x0000F000                // MDPIF_DBG[15..12]
#define WF_WTBLON_TOP_DFR_MDPIF_DBG_SHFT                       12
#define WF_WTBLON_TOP_DFR_MUCOPIF_DEB_ADDR                     WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_MUCOPIF_DEB_MASK                     0x00000F00                // MUCOPIF_DEB[11..8]
#define WF_WTBLON_TOP_DFR_MUCOPIF_DEB_SHFT                     8
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_ADDR                       WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_MASK                       0x000000FF                // SRAMIF_CS[7..0]
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_SHFT                       0

/* =====================================================================================

  ---DBG (0x820D4000 + 0x0404)---

    DBG_USER_SEL[5..0]           - (RW) Select the user for debug flag
    RESERVED6[14..6]             - (RO) Reserved bits
    DBG_MODE[15]                 - (RW) debug mode
    RESERVED16[30..16]           - (RO) Reserved bits
    CKEN_ERROR[31]               - (RO) HW debug info

 =====================================================================================*/
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_ADDR                      WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_MASK                      0x80000000                // CKEN_ERROR[31]
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_SHFT                      31
#define WF_WTBLON_TOP_DBG_DBG_MODE_ADDR                        WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_MODE_MASK                        0x00008000                // DBG_MODE[15]
#define WF_WTBLON_TOP_DBG_DBG_MODE_SHFT                        15
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_ADDR                    WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_MASK                    0x0000003F                // DBG_USER_SEL[5..0]
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_SHFT                    0

/* =====================================================================================

  ---DMY0 (0x820D4000 + 0x04F0)---

    DMY0[31..0]                  - (RW) Dummy Register with default value 0 for ECO purpose
                                     [31:16] : wtbloff
                                     [15:0] : wtblon

 =====================================================================================*/
#define WF_WTBLON_TOP_DMY0_DMY0_ADDR                           WF_WTBLON_TOP_DMY0_ADDR
#define WF_WTBLON_TOP_DMY0_DMY0_MASK                           0xFFFFFFFF                // DMY0[31..0]
#define WF_WTBLON_TOP_DMY0_DMY0_SHFT                           0

/* =====================================================================================

  ---DMY1 (0x820D4000 + 0x04F4)---

    DMY1[31..0]                  - (RW) Dummy Register with default value 1 for ECO purpose
                                     [31:16] : wtbloff
                                     [15:0] : wtblon

 =====================================================================================*/
#define WF_WTBLON_TOP_DMY1_DMY1_ADDR                           WF_WTBLON_TOP_DMY1_ADDR
#define WF_WTBLON_TOP_DMY1_DMY1_MASK                           0xFFFFFFFF                // DMY1[31..0]
#define WF_WTBLON_TOP_DMY1_DMY1_SHFT                           0

#ifdef __cplusplus
}
#endif

#endif // __WF_WTBLON_TOP_REGS_H__
