#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=60

start() {
	WX=$(uci -q get custom.bwallocate.lock)
	if [ "$WX" = "1" ]; then
		uci set bwmon.general.enabled=$enable
		uci commit bwmon
	fi
	/usr/lib/bwmon/wrtbwmon.sh &
	/usr/lib/bwmon/create.sh &
}

stop() {
	rmdir -f /tmp/WRTbmon
}