#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

if ! uci -q get system.@imm_init[0].dhcp > "/dev/null"; then
	uci -q batch <<-EOF
		set dhcp.@dnsmasq[0].logfacility="/dev/null"
		commit dhcp

		set system.@imm_init[0].dhcp="1"
		commit system
	EOF
fi

ln -sf "/sbin/ip" "/usr/bin/ip"

exit 0
