#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@clash[-1]
	add ucitrack clash
	set ucitrack.@clash[-1].init=clash
	commit ucitrack
EOF
chmod 777 /etc/init.d/clash
rm -f /tmp/luci-indexcache
exit 0
