#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=50
USE_PROCD=1

log() {
	logger -t "WatchDog" "$@"
}

start_service()
{
	dis=486
	echo $dis > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$dis/direction
	echo 0 >/sys/class/gpio/gpio$dis/value
}
