# LuCI Theme Infinity Freedom
# Copyright 2020 Richard Yu <xiaoqingfengatgm@gmail.com>
#
# Licensed under the Apache License v2.0
# http://www.apache.org/licenses/LICENSE-2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Infinity Freedom Theme
LUCI_DEPENDS:=+libc

PKG_NAME:=luci-theme-infinityfreedom
PKG_VERSION:=1.4.20200613
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
