include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-xlnetacc
PKG_VERSION:=1.0.5
PKG_RELEASE:=2

PKG_LICENSE:=GPLv2
PKG_MAINTAINER:=Sense <sensec@gmail.com>
LUCI_TITLE:=LuCI Support for XLNetAcc
LUCI_DEPENDS:=+jshn +wget-ssl +openssl-util
LUCI_PKGARCH:=all
LUCI_DESCRIPTION=LuCI Support for XLNetAcc.

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
