#
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for softethervpn5
LUCI_DEPENDS:= +softethervpn5-server +softethervpn5-bridge +softethervpn5-client
PKG_VERSION:=1.09

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
