include $(TOPDIR)/rules.mk

LUCI_TITLE:=SMS Tool for 3G Modem
LUCI_DESCRIPTION:=This package contains sms tool for 3G Modem
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-smstool
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

