#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 Jian Chang <aa65535@live.com>, Ian Li
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

xappend() {
	parms="$parms $1"
}

append_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _loctmp
	config_get_bool _loctmp "$section" "$option"
	[ "$_loctmp" = 1 ] || return 0
	xappend "$value"
}

append_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local _loctmp
	config_get _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && return 0
	xappend "$switch $_loctmp"
}

start_chinadns() {
	local enable
	local yn_use_proxy
	local local_subnet=$(echo `curl -4 -s members.3322.org/dyndns/getip | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.'`0)
	config_get_bool enable $1 enable
	[ "$enable" = 1 ] || return 0
	config_get_bool yn_use_proxy $1 yn_use_proxy
	[ "$yn_use_proxy" = 0 ] && local foreign_subnet && config_get foreign_subnet $1 foreign_subnet
	[ "$yn_use_proxy" = 1 ] && local foregin_subnet=$(echo `curl -4 -s ip.sb | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.'`0)
	append_parm $1 port "-p"
	append_parm $1 server "-s"
	append_parm $1 chnroute "-c"
	xappend "-e $local_subnet,$foreign_subnet"
	service_start /usr/sbin/chinadns \
		$parms
	return $?
}

start() {
	config_load chinadns
	config_foreach start_chinadns chinadns
}

stop() {
	service_stop /usr/sbin/chinadns
}
