#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

PROG=/usr/sbin/https_dns_proxy

xappend() { param="$param $1"; }

append_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local default="$4"
	local _loctmp
	config_get _loctmp "$section" "$option" "$default"
	[ -z "$_loctmp" ] && return 0
	xappend "$switch $_loctmp"
}

start_instance() {
	local cfg="$1" param

	append_parm "$cfg" 'listen_addr' '-a' '127.0.0.1'
	append_parm "$cfg" 'listen_port' '-p' '5053'
	append_parm "$cfg" 'bootstrap_dns' '-b'
	append_parm "$cfg" 'url_prefix' '-r'
	append_parm "$cfg" 'user' '-u' 'nobody'
	append_parm "$cfg" 'group' '-g' 'nogroup'
	append_parm "$cfg" 'subnet_addr' '-e'
	append_parm "$cfg" 'proxy_server' '-t'

	procd_open_instance
	procd_set_param command ${PROG} ${param}
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "https_dns_proxy"
}

start_service() {
	config_load 'https_dns_proxy'
	config_foreach start_instance 'https_dns_proxy'
}
