#
# Copyright (C) 2019 mleaf <mleaf90@gmail.com>
# 微信公众号【WiFi物联网】
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Mwol
LUCI_DEPENDS:=+mwol
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
