#!/bin/sh /etc/rc.common
# Created By [CTCGFW]Project OpenWRT
# https://github.com/project-openwrt

START=99
STOP=10

lan_addr="$(uci get network.lan.ipaddr)"

enable="$(uci get unblockneteasemusic.@unblockneteasemusic[0].enabled)"
http_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].http_port)"
https_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].https_port)"
type="$(uci get unblockneteasemusic.@unblockneteasemusic[0].musicapptype)"
hijack_ways="$(uci get unblockneteasemusic.@unblockneteasemusic[0].hijack_ways)"
auto_update="$(uci get unblockneteasemusic.@unblockneteasemusic[0].auto_update)"
[ "*$(uci get unblockneteasemusic.@unblockneteasemusic[0].pub_access 2>/dev/null)*" = "*1*" ] && addr="0.0.0.0" || addr="${lan_addr}"
[ "*$(uci get unblockneteasemusic.@unblockneteasemusic[0].strict_mode 2>/dev/null)*" = "*1*" ] && strict_mode="-s"

netease_server_ip="$(uci get unblockneteasemusic.@unblockneteasemusic[0].netease_server_ip 2>/dev/null)"
[ -n "${netease_server_ip}" ] && netease_server_ip="-f ${netease_server_ip}"
endpoint_url="$(uci get unblockneteasemusic.@unblockneteasemusic[0].endpoint_url 2>/dev/null)"
[ -n "${endpoint_url}" ] && endpoint_url="-e ${endpoint_url}"
proxy_server_ip="$(uci get unblockneteasemusic.@unblockneteasemusic[0].proxy_server_ip 2>/dev/null)"
[ -n "${proxy_server_ip}" ] && proxy_server_ip="-u ${proxy_server_ip}"

set_ipset(){
	if [ "${set_type}" = "start" ]; then
		mkdir -p "/tmp/dnsmasq.d"
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
		echo "dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac" > "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
		echo "ipset=/.music.163.com/music" >> "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
		echo "ipset=/interface.music.163.com/music" >> "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
		/etc/init.d/dnsmasq restart >/dev/null 2>&1

		if ! ipset list music >/dev/null; then ipset create music hash:ip; fi
		bash <(curl -s "http://httpdns.n.netease.com/httpdns/v2/d?domain=p2.music.126.net,interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,apm.music.163.com,apm3.music.163.com,p1.music.126.net,clientlog3.music.163.com" |grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' |sort |uniq |awk '{print "ipset add music "$1}') >/dev/null 2>&1
		iptables -t nat -N cloud_music
		iptables -t nat -A cloud_music -d 0.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music -d 10.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music -d 127.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music -d 169.254.0.0/16 -j RETURN
		iptables -t nat -A cloud_music -d 172.16.0.0/12 -j RETURN
		iptables -t nat -A cloud_music -d 192.168.0.0/16 -j RETURN
		iptables -t nat -A cloud_music -d 224.0.0.0/4 -j RETURN
		iptables -t nat -A cloud_music -d 240.0.0.0/4 -j RETURN
		iptables -t nat -A cloud_music -p tcp --dport 80 -j REDIRECT --to-ports "${http_port}"
		iptables -t nat -A cloud_music -p tcp --dport 443 -j REDIRECT --to-ports "${https_port}"
		iptables -t nat -I PREROUTING -p tcp -m set --match-set music dst -j cloud_music

		mkdir -p /var/etc
		cat <<-EOF > "/var/etc/unblockneteasemusic.include"
if ! ipset list music >/dev/null; then ipset create music hash:ip; fi
bash <(curl -s http://httpdns.n.netease.com/httpdns/v2/d?domain=p2.music.126.net,interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,apm.music.163.com,apm3.music.163.com,p1.music.126.net,clientlog3.music.163.com |grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' |sort |uniq |awk '{print "ipset add music "$1}') >/dev/null 2>&1
iptables -t nat -N cloud_music
iptables -t nat -A cloud_music -d 0.0.0.0/8 -j RETURN
iptables -t nat -A cloud_music -d 10.0.0.0/8 -j RETURN
iptables -t nat -A cloud_music -d 127.0.0.0/8 -j RETURN
iptables -t nat -A cloud_music -d 169.254.0.0/16 -j RETURN
iptables -t nat -A cloud_music -d 172.16.0.0/12 -j RETURN
iptables -t nat -A cloud_music -d 192.168.0.0/16 -j RETURN
iptables -t nat -A cloud_music -d 224.0.0.0/4 -j RETURN
iptables -t nat -A cloud_music -d 240.0.0.0/4 -j RETURN
iptables -t nat -A cloud_music -p tcp --dport 80 -j REDIRECT --to-ports ${http_port}
iptables -t nat -A cloud_music -p tcp --dport 443 -j REDIRECT --to-ports ${https_port}
iptables -t nat -I PREROUTING -p tcp -m set --match-set music dst -j cloud_music
		EOF
	elif [ "${set_type}" = "stop" ]; then
		iptables -t nat -D PREROUTING -p tcp -m set --match-set music dst -j cloud_music
		iptables -t nat -F cloud_music
		iptables -t nat -X cloud_music
		ipset destroy music

		echo "" > "/var/etc/unblockneteasemusic.include"
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
		/etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi
}

set_hosts(){
	if [ "${set_type}" = "start" ]; then
		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='music.163.com'
		uci set dhcp."${cfg_name}".ip="$(uci get network.lan.ipaddr)"
		uci commit dhcp

		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='interface.music.163.com'
		uci set dhcp."${cfg_name}".ip="$(uci get network.lan.ipaddr)"
		uci commit dhcp

		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='music.httpdns.c.163.com'
		uci set dhcp."${cfg_name}".ip="127.0.0.1"
		uci commit dhcp

		ip route add 223.252.199.10 dev lo
	elif [ "${set_type}" = "stop" ]; then
		music_id1="$(uci show dhcp| grep "interface.music.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		uci delete dhcp.@domain["${music_id1}"]
		uci commit dhcp

		music_id2="$(uci show dhcp| grep "music.httpdns.c.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		uci delete dhcp.@domain["${music_id2}"]
		uci commit dhcp

		music_id3="$(uci show dhcp| grep "music.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		uci delete dhcp.@domain["${music_id3}"]
		uci commit dhcp

		ip route del 223.252.199.10
	fi
}

start()
{
	stop

	[ "${enable}" -eq "0" ] && exit 0

	[ ! -e "/usr/share/unblockneteasemusic/core/app.js" ] && bash /usr/share/unblockneteasemusic/update_core.sh && [ $? -eq 1 ] && exit 1

	if [ "${type}" = "default" ]; then
		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >>/tmp/unblockneteasemusic.log 2>&1 &
	elif [ "${type}" = "all" ]; then
		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" -o "kuwo migu qq xiami kugou joox" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >>/tmp/unblockneteasemusic.log 2>&1 &
	else
		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" -o "${type}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >>/tmp/unblockneteasemusic.log 2>&1 &
	fi

	if [ "*${hijack_ways}*" = "*use_ipset*" ]; then
		set_type="start"
		set_ipset >/dev/null 2>&1
	elif [ "*${hijack_ways}*" = "*use_hosts*" ]; then
		set_type="start"
		set_hosts >/dev/null 2>&1
	fi

	sed -i '/unblockneteasemusic/d' /etc/crontabs/root
	[ "${auto_update}" -eq "1" ] && echo "30 3 * * * /usr/share/unblockneteasemusic/update_core.sh" >> "/etc/crontabs/root"
	echo "*/5 * * * * /usr/share/unblockneteasemusic/log_check.sh" >> "/etc/crontabs/root"
	/etc/init.d/cron restart >/dev/null 2>&1
}

stop()
{
	{ ps |grep "unblockneteasemusic" |grep "app.js" |grep -v "grep" |awk '{print $1}' |xargs kill -9; } >/dev/null 2>&1
 
	sed -i '/unblockneteasemusic/d' /etc/crontabs/root
	/etc/init.d/cron restart >/dev/null 2>&1

	rm -f /tmp/unblockneteasemusic.log

	set_type="stop"
	set_ipset >/dev/null 2>&1
	set_hosts >/dev/null 2>&1
}
