#!/bin/sh

if command -v vcgencmd >/dev/null; then
	cpu_freq="$(vcgencmd get_config arm_freq | awk -F '=' '{print $2}')Mhz"
	sys_temp="$(vcgencmd measure_temp | grep -Eo '[0-9.]+')°C"
else
	cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq) / 1000)Mhz"
	sys_temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"
fi

echo -n "(${cpu_freq}, ${sys_temp})"
