#!/bin/sh

if [ -z "$${IPKG_INSTROOT}" ]; then
	uci -q batch <<-EOF >/dev/null
		delete firewall.brook
		set firewall.brook=include
		set firewall.brook.type=script
		set firewall.brook.path=/var/etc/brook.include
		set firewall.brook.reload=1
		commit firewall
EOF
	( . /etc/uci-defaults/luci-brook ) && rm -f /etc/uci-defaults/luci-brook
	chmod 755 /etc/init.d/brook >/dev/null 2>&1
	/etc/init.d/brook enable >/dev/null 2>&1
fi
exit 0
