#!/bin/sh
# check if we are on real system
if [ -z "$${IPKG_INSTROOT}" ]; then
	echo "Removing rc.d symlink for brook"
	/etc/init.d/brook disable
	/etc/init.d/brook stop
	echo "Removing firewall rule for brook"
	uci -q batch <<-EOF >/dev/null
		delete firewall.brook
		commit firewall
EOF
	sed -i '/conf-dir/d' /etc/dnsmasq.conf
	/etc/init.d/dnsmasq restart

fi
exit 0
