//[File]            : conn_mcu_bus_cr.h
//[Revision time]   : Thu Apr 29 14:30:33 2021
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2021 Mediatek Incorportion. All rights reserved.

#ifndef __CONN_MCU_BUS_CR_REGS_H__
#define __CONN_MCU_BUS_CR_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CONN_MCU_BUS_CR CR Definitions                     
//
//****************************************************************************

#define CONN_MCU_BUS_CR_BASE                                   0x830C0000

#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_ADDR                     (CONN_MCU_BUS_CR_BASE + 0x114) // 0114
#define CONN_MCU_BUS_CR_AP2WF_REMAP_0_ADDR                     (CONN_MCU_BUS_CR_BASE + 0x011C) // 011C
#define CONN_MCU_BUS_CR_AP2WF_REMAP_1_ADDR                     (CONN_MCU_BUS_CR_BASE + 0x0120) // 0120
#define CONN_MCU_BUS_CR_AP2WF_REMAP_2_ADDR                     (CONN_MCU_BUS_CR_BASE + 0x0124) // 0124
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_0_ADDR                 (CONN_MCU_BUS_CR_BASE + 0x0128) // 0128
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_1_ADDR                 (CONN_MCU_BUS_CR_BASE + 0x012C) // 012C
#define CONN_MCU_BUS_CR_AP2WF_REMAP_3_ADDR                     (CONN_MCU_BUS_CR_BASE + 0x0134) // 0134
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_0_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01B0) // 01B0
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_1_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01B4) // 01B4
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01B8) // 01B8
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01BC) // 01BC
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01C0) // 01C0
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01C4) // 01C4
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_6_ADDR               (CONN_MCU_BUS_CR_BASE + 0x01C8) // 01C8
#define CONN_MCU_BUS_CR_AXI_ULTRA_ADDR                         (CONN_MCU_BUS_CR_BASE + 0x01d4) // 01D4
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_ADDR                  (CONN_MCU_BUS_CR_BASE + 0x01d8) // 01D8
#define CONN_MCU_BUS_CR_WM_PROT_EN_ADDR                        (CONN_MCU_BUS_CR_BASE + 0x0C00) // 0C00
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_CLEAR_ADDR                 (CONN_MCU_BUS_CR_BASE + 0x0C04) // 0C04
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR                   (CONN_MCU_BUS_CR_BASE + 0x0C08) // 0C08
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_0_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C0C) // 0C0C
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_0_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C10) // 0C10
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_1_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C14) // 0C14
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_1_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C18) // 0C18
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_2_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C1C) // 0C1C
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_2_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C20) // 0C20
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_3_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C24) // 0C24
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_3_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C28) // 0C28
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_4_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C2C) // 0C2C
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_4_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C30) // 0C30
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_5_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C34) // 0C34
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_5_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C38) // 0C38
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_6_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C3C) // 0C3C
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_6_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C40) // 0C40
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_7_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C44) // 0C44
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_7_ADDR                (CONN_MCU_BUS_CR_BASE + 0x0C48) // 0C48
#define CONN_MCU_BUS_CR_WM_PROT_ADDR_FETCH_CLR_ADDR            (CONN_MCU_BUS_CR_BASE + 0x0C4C) // 0C4C
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_ADDR_FETCH_ADDR            (CONN_MCU_BUS_CR_BASE + 0x0C50) // 0C50
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_EN_ADDR                   (CONN_MCU_BUS_CR_BASE + 0x0C60) // 0C60
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_CLR_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C64) // 0C64
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0C68) // 0C68
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_0_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0C6C) // 0C6C
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_0_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0C70) // 0C70
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_1_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0C74) // 0C74
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_1_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0C78) // 0C78
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_2_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0C7C) // 0C7C
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_2_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0C80) // 0C80
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_3_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0C84) // 0C84
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_3_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0C88) // 0C88
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_ADDR_FETCH_CLR_ADDR       (CONN_MCU_BUS_CR_BASE + 0x0C8C) // 0C8C
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_ADDR_FETCH_ADDR       (CONN_MCU_BUS_CR_BASE + 0x0C90) // 0C90
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_EN_ADDR                   (CONN_MCU_BUS_CR_BASE + 0x0CA0) // 0CA0
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_CLR_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0CA4) // 0CA4
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0CA8) // 0CA8
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_0_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0CAC) // 0CAC
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_0_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0CB0) // 0CB0
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_1_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0CB4) // 0CB4
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_1_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0CB8) // 0CB8
#define CONN_MCU_BUS_CR_MDBT_1_PROT_START_ADDR_2_ADDR          (CONN_MCU_BUS_CR_BASE + 0x0CBC) // 0CBC
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_2_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0CC0) // 0CC0
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_3_ADDR         (CONN_MCU_BUS_CR_BASE + 0x0CC4) // 0CC4
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_3_ADDR           (CONN_MCU_BUS_CR_BASE + 0x0CC8) // 0CC8
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_ADDR_FETCH_CLR_ADDR       (CONN_MCU_BUS_CR_BASE + 0x0CCC) // 0CCC
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_ADDR_FETCH_ADDR       (CONN_MCU_BUS_CR_BASE + 0x0CD0) // 0CD0
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_ADDR              (CONN_MCU_BUS_CR_BASE + 0x0CE0) // 0CE0




/* =====================================================================================

  ---WF2AP_REMAP_0 (0x830C0000 + 0x114)---

    R_CONN_INFRA_START_ADDRESS_IN_AP[7..0] - (RW)  xxx 
    RESERVED8[15..8]             - (RO) Reserved bits
    R_CONN_INFRA_START_ADDRESS_IN_WF[23..16] - (RW)  xxx 
    RESERVED24[31..24]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_WF_ADDR CONN_MCU_BUS_CR_WF2AP_REMAP_0_ADDR
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_WF_MASK 0x00FF0000                // R_CONN_INFRA_START_ADDRESS_IN_WF[23..16]
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_WF_SHFT 16
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_AP_ADDR CONN_MCU_BUS_CR_WF2AP_REMAP_0_ADDR
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_AP_MASK 0x000000FF                // R_CONN_INFRA_START_ADDRESS_IN_AP[7..0]
#define CONN_MCU_BUS_CR_WF2AP_REMAP_0_R_CONN_INFRA_START_ADDRESS_IN_AP_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_0 (0x830C0000 + 0x011C)---

    R_AP2WF_PRIVAT_REMAPPING_0_START_ADDRESS[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_0_R_AP2WF_PRIVAT_REMAPPING_0_START_ADDRESS_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_0_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_0_R_AP2WF_PRIVAT_REMAPPING_0_START_ADDRESS_MASK 0xFFFFFFFF                // R_AP2WF_PRIVAT_REMAPPING_0_START_ADDRESS[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_0_R_AP2WF_PRIVAT_REMAPPING_0_START_ADDRESS_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_1 (0x830C0000 + 0x0120)---

    R_AP2WF_PUBLIC_REMAPPING_0_START_ADDRESS[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_1_R_AP2WF_PUBLIC_REMAPPING_0_START_ADDRESS_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_1_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_1_R_AP2WF_PUBLIC_REMAPPING_0_START_ADDRESS_MASK 0xFFFFFFFF                // R_AP2WF_PUBLIC_REMAPPING_0_START_ADDRESS[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_1_R_AP2WF_PUBLIC_REMAPPING_0_START_ADDRESS_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_2 (0x830C0000 + 0x0124)---

    R_AP2WF_PUBLIC_REMAPPING_1_START_ADDRESS[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_2_R_AP2WF_PUBLIC_REMAPPING_1_START_ADDRESS_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_2_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_2_R_AP2WF_PUBLIC_REMAPPING_1_START_ADDRESS_MASK 0xFFFFFFFF                // R_AP2WF_PUBLIC_REMAPPING_1_START_ADDRESS[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_2_R_AP2WF_PUBLIC_REMAPPING_1_START_ADDRESS_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_SEG_0 (0x830C0000 + 0x0128)---

    R_AP2WF_REMAPPING_SEGMENT_0[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_0_R_AP2WF_REMAPPING_SEGMENT_0_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_0_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_0_R_AP2WF_REMAPPING_SEGMENT_0_MASK 0xFFFFFFFF                // R_AP2WF_REMAPPING_SEGMENT_0[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_0_R_AP2WF_REMAPPING_SEGMENT_0_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_SEG_1 (0x830C0000 + 0x012C)---

    R_AP2WF_REMAPPING_SEGMENT_1[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_1_R_AP2WF_REMAPPING_SEGMENT_1_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_1_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_1_R_AP2WF_REMAPPING_SEGMENT_1_MASK 0xFFFFFFFF                // R_AP2WF_REMAPPING_SEGMENT_1[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_SEG_1_R_AP2WF_REMAPPING_SEGMENT_1_SHFT 0

/* =====================================================================================

  ---AP2WF_REMAP_3 (0x830C0000 + 0x0134)---

    R_AP2WF_WF_START_ADDRESS[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AP2WF_REMAP_3_R_AP2WF_WF_START_ADDRESS_ADDR CONN_MCU_BUS_CR_AP2WF_REMAP_3_ADDR
#define CONN_MCU_BUS_CR_AP2WF_REMAP_3_R_AP2WF_WF_START_ADDRESS_MASK 0xFFFFFFFF                // R_AP2WF_WF_START_ADDRESS[31..0]
#define CONN_MCU_BUS_CR_AP2WF_REMAP_3_R_AP2WF_WF_START_ADDRESS_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_0 (0x830C0000 + 0x01B0)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP0[19..0] - (RW)  xxx 
    RESERVED20[31..20]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_0_R_CONNAC_LEGACY_AP2WF_ADDR_MAP0_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_0_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_0_R_CONNAC_LEGACY_AP2WF_ADDR_MAP0_MASK 0x000FFFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP0[19..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_0_R_CONNAC_LEGACY_AP2WF_ADDR_MAP0_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_1 (0x830C0000 + 0x01B4)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP1[19..0] - (RW)  xxx 
    RESERVED20[31..20]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_1_R_CONNAC_LEGACY_AP2WF_ADDR_MAP1_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_1_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_1_R_CONNAC_LEGACY_AP2WF_ADDR_MAP1_MASK 0x000FFFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP1[19..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_1_R_CONNAC_LEGACY_AP2WF_ADDR_MAP1_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_2 (0x830C0000 + 0x01B8)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP2[15..0] - (RW)  xxx 
    R_CONNAC_LEGACY_AP2WF_ADDR_MAP3[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP3_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP3_MASK 0xFFFF0000                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP3[31..16]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP3_SHFT 16
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP2_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP2_MASK 0x0000FFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP2[15..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_2_R_CONNAC_LEGACY_AP2WF_ADDR_MAP2_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_3 (0x830C0000 + 0x01BC)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP4[15..0] - (RW)  xxx 
    R_CONNAC_LEGACY_AP2WF_ADDR_MAP5[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP5_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP5_MASK 0xFFFF0000                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP5[31..16]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP5_SHFT 16
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP4_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP4_MASK 0x0000FFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP4[15..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_3_R_CONNAC_LEGACY_AP2WF_ADDR_MAP4_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_4 (0x830C0000 + 0x01C0)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP6[15..0] - (RW)  xxx 
    R_CONNAC_LEGACY_AP2WF_ADDR_MAP7[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP7_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP7_MASK 0xFFFF0000                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP7[31..16]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP7_SHFT 16
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP6_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP6_MASK 0x0000FFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP6[15..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_4_R_CONNAC_LEGACY_AP2WF_ADDR_MAP6_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_5 (0x830C0000 + 0x01C4)---

    R_CONNAC_LEGACY_AP2WF_ADDR_MAP8[15..0] - (RW)  xxx 
    R_CONNAC_LEGACY_AP2WF_ADDR_MAP9[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP9_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP9_MASK 0xFFFF0000                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP9[31..16]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP9_SHFT 16
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP8_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP8_MASK 0x0000FFFF                // R_CONNAC_LEGACY_AP2WF_ADDR_MAP8[15..0]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_5_R_CONNAC_LEGACY_AP2WF_ADDR_MAP8_SHFT 0

/* =====================================================================================

  ---LEGACY_REMAP_CTRL_6 (0x830C0000 + 0x01C8)---

    RESERVED0[0]                 - (RO) Reserved bits
    R_CONNAC_LEGACY_AP2WF_MAPPER_ENABLE[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_6_R_CONNAC_LEGACY_AP2WF_MAPPER_ENABLE_ADDR CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_6_ADDR
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_6_R_CONNAC_LEGACY_AP2WF_MAPPER_ENABLE_MASK 0x00000002                // R_CONNAC_LEGACY_AP2WF_MAPPER_ENABLE[1]
#define CONN_MCU_BUS_CR_LEGACY_REMAP_CTRL_6_R_CONNAC_LEGACY_AP2WF_MAPPER_ENABLE_SHFT 1

/* =====================================================================================

  ---AXI_ULTRA (0x830C0000 + 0x01d4)---

    WF_AXIDMA_M0_ARULTRA[1..0]   - (RW)  xxx 
    WF_AXIDMA_M0_AWULTRA[3..2]   - (RW)  xxx 
    WF_AXIDMA_M1_ARULTRA[5..4]   - (RW)  xxx 
    WF_AXIDMA_M1_AWULTRA[7..6]   - (RW)  xxx 
    WA_CPU_WRAPPER_M_ARULTRA[9..8] - (RW)  xxx 
    WA_CPU_WRAPPER_M_AWULTRA[11..10] - (RW)  xxx 
    WM_CPU_WRAPPER_M_ARULTRA[13..12] - (RW)  xxx 
    WM_CPU_WRAPPER_M_AWULTRA[15..14] - (RW)  xxx 
    WF_S1_M_ARULTRA[17..16]      - (RW)  xxx 
    WF_S1_M_AWULTRA[19..18]      - (RW)  xxx 
    WF_HIF_WFDMA0_M0_ARULTRA[21..20] - (RW)  xxx 
    WF_HIF_WFDMA0_M0_AWULTRA[23..22] - (RW)  xxx 
    WF_HIF_WFDMA1_M0_ARULTRA[25..24] - (RW)  xxx 
    WF_HIF_WFDMA1_M0_AWULTRA[27..26] - (RW)  xxx 
    WF_SDO_M0_ARULTRA[29..28]    - (RW)  xxx 
    WF_SDO_M0_AWULTRA[31..30]    - (RW)  xxx 

 =====================================================================================*/
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_AWULTRA_ADDR       CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_AWULTRA_MASK       0xC0000000                // WF_SDO_M0_AWULTRA[31..30]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_AWULTRA_SHFT       30
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_ARULTRA_ADDR       CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_ARULTRA_MASK       0x30000000                // WF_SDO_M0_ARULTRA[29..28]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_SDO_M0_ARULTRA_SHFT       28
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_AWULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_AWULTRA_MASK 0x0C000000                // WF_HIF_WFDMA1_M0_AWULTRA[27..26]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_AWULTRA_SHFT 26
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_ARULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_ARULTRA_MASK 0x03000000                // WF_HIF_WFDMA1_M0_ARULTRA[25..24]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA1_M0_ARULTRA_SHFT 24
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_AWULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_AWULTRA_MASK 0x00C00000                // WF_HIF_WFDMA0_M0_AWULTRA[23..22]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_AWULTRA_SHFT 22
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_ARULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_ARULTRA_MASK 0x00300000                // WF_HIF_WFDMA0_M0_ARULTRA[21..20]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_HIF_WFDMA0_M0_ARULTRA_SHFT 20
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_AWULTRA_ADDR         CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_AWULTRA_MASK         0x000C0000                // WF_S1_M_AWULTRA[19..18]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_AWULTRA_SHFT         18
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_ARULTRA_ADDR         CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_ARULTRA_MASK         0x00030000                // WF_S1_M_ARULTRA[17..16]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_S1_M_ARULTRA_SHFT         16
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_AWULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_AWULTRA_MASK 0x0000C000                // WM_CPU_WRAPPER_M_AWULTRA[15..14]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_AWULTRA_SHFT 14
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_ARULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_ARULTRA_MASK 0x00003000                // WM_CPU_WRAPPER_M_ARULTRA[13..12]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WM_CPU_WRAPPER_M_ARULTRA_SHFT 12
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_AWULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_AWULTRA_MASK 0x00000C00                // WA_CPU_WRAPPER_M_AWULTRA[11..10]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_AWULTRA_SHFT 10
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_ARULTRA_ADDR CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_ARULTRA_MASK 0x00000300                // WA_CPU_WRAPPER_M_ARULTRA[9..8]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WA_CPU_WRAPPER_M_ARULTRA_SHFT 8
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_AWULTRA_ADDR    CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_AWULTRA_MASK    0x000000C0                // WF_AXIDMA_M1_AWULTRA[7..6]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_AWULTRA_SHFT    6
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_ARULTRA_ADDR    CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_ARULTRA_MASK    0x00000030                // WF_AXIDMA_M1_ARULTRA[5..4]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M1_ARULTRA_SHFT    4
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_AWULTRA_ADDR    CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_AWULTRA_MASK    0x0000000C                // WF_AXIDMA_M0_AWULTRA[3..2]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_AWULTRA_SHFT    2
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_ARULTRA_ADDR    CONN_MCU_BUS_CR_AXI_ULTRA_ADDR
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_ARULTRA_MASK    0x00000003                // WF_AXIDMA_M0_ARULTRA[1..0]
#define CONN_MCU_BUS_CR_AXI_ULTRA_WF_AXIDMA_M0_ARULTRA_SHFT    0

/* =====================================================================================

  ---VDNR_PWR_PROT_CR (0x830C0000 + 0x01d8)---

    VDNR_PWR_PROT_EN[1..0]       - (RW)  xxx 
    VDNR_PWR_PROT_SW[3..2]       - (RW)  xxx 
    VDNR_PWR_PROT_RDY[5..4]      - (RO)  xxx 
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_RDY_ADDR CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_ADDR
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_RDY_MASK 0x00000030                // VDNR_PWR_PROT_RDY[5..4]
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_RDY_SHFT 4
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_SW_ADDR CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_ADDR
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_SW_MASK 0x0000000C                // VDNR_PWR_PROT_SW[3..2]
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_SW_SHFT 2
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_EN_ADDR CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_ADDR
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_EN_MASK 0x00000003                // VDNR_PWR_PROT_EN[1..0]
#define CONN_MCU_BUS_CR_VDNR_PWR_PROT_CR_VDNR_PWR_PROT_EN_SHFT 0

/* =====================================================================================

  ---WM_PROT_EN (0x830C0000 + 0x0C00)---

    WM_PROT_EN[0]                - (RW) wf_mcu_bus access portect en for wm
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_EN_WM_PROT_EN_ADDR             CONN_MCU_BUS_CR_WM_PROT_EN_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_EN_WM_PROT_EN_MASK             0x00000001                // WM_PROT_EN[0]
#define CONN_MCU_BUS_CR_WM_PROT_EN_WM_PROT_EN_SHFT             0

/* =====================================================================================

  ---WM_PROT_IRQ_CLEAR (0x830C0000 + 0x0C04)---

    WM_PROT_IRQ_CLR[0]           - (RW) wf_mcu_bus access portect irq clear for wm
                                     write 1 to clear irq and after irq clr, you need to write 0
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_CLEAR_WM_PROT_IRQ_CLR_ADDR CONN_MCU_BUS_CR_WM_PROT_IRQ_CLEAR_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_CLEAR_WM_PROT_IRQ_CLR_MASK 0x00000001                // WM_PROT_IRQ_CLR[0]
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_CLEAR_WM_PROT_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---WM_PROT_WR_CTRL (0x830C0000 + 0x0C08)---

    WM_PROT_WR_CTRL_0[1..0]      - (RW) Portect_0_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_1[3..2]      - (RW) Portect_1_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_2[5..4]      - (RW) Portect_2_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_3[7..6]      - (RW) Portect_3_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_4[9..8]      - (RW) Portect_4_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_5[11..10]    - (RW) Portect_5_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_6[13..12]    - (RW) Portect_6_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    WM_PROT_WR_CTRL_7[15..14]    - (RW) Portect_7_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_7_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_7_MASK 0x0000C000                // WM_PROT_WR_CTRL_7[15..14]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_7_SHFT 14
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_6_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_6_MASK 0x00003000                // WM_PROT_WR_CTRL_6[13..12]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_6_SHFT 12
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_5_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_5_MASK 0x00000C00                // WM_PROT_WR_CTRL_5[11..10]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_5_SHFT 10
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_4_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_4_MASK 0x00000300                // WM_PROT_WR_CTRL_4[9..8]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_4_SHFT 8
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_3_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_3_MASK 0x000000C0                // WM_PROT_WR_CTRL_3[7..6]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_3_SHFT 6
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_2_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_2_MASK 0x00000030                // WM_PROT_WR_CTRL_2[5..4]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_2_SHFT 4
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_1_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_1_MASK 0x0000000C                // WM_PROT_WR_CTRL_1[3..2]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_1_SHFT 2
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_0_ADDR CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_0_MASK 0x00000003                // WM_PROT_WR_CTRL_0[1..0]
#define CONN_MCU_BUS_CR_WM_PROT_WR_CTRL_WM_PROT_WR_CTRL_0_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_0 (0x830C0000 + 0x0C0C)---

    WM_PROT_START_ADDR_0[31..0]  - (RW) Portect_0 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_0_WM_PROT_START_ADDR_0_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_0_WM_PROT_START_ADDR_0_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_0_WM_PROT_START_ADDR_0_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_0 (0x830C0000 + 0x0C10)---

    WM_PROT_END_ADDR_0[31..0]    - (RW) Portect_0 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_0_WM_PROT_END_ADDR_0_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_0_WM_PROT_END_ADDR_0_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_0_WM_PROT_END_ADDR_0_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_1 (0x830C0000 + 0x0C14)---

    WM_PROT_START_ADDR_1[31..0]  - (RW) Portect_1 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_1_WM_PROT_START_ADDR_1_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_1_WM_PROT_START_ADDR_1_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_1_WM_PROT_START_ADDR_1_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_1 (0x830C0000 + 0x0C18)---

    WM_PROT_END_ADDR_1[31..0]    - (RW) Portect_1 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_1_WM_PROT_END_ADDR_1_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_1_WM_PROT_END_ADDR_1_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_1_WM_PROT_END_ADDR_1_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_2 (0x830C0000 + 0x0C1C)---

    WM_PROT_START_ADDR_2[31..0]  - (RW) Portect_2 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_2_WM_PROT_START_ADDR_2_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_2_WM_PROT_START_ADDR_2_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_2_WM_PROT_START_ADDR_2_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_2 (0x830C0000 + 0x0C20)---

    WM_PROT_END_ADDR_2[31..0]    - (RW) Portect_2 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_2_WM_PROT_END_ADDR_2_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_2_WM_PROT_END_ADDR_2_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_2_WM_PROT_END_ADDR_2_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_3 (0x830C0000 + 0x0C24)---

    WM_PROT_START_ADDR_3[31..0]  - (RW) Portect_3 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_3_WM_PROT_START_ADDR_3_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_3_WM_PROT_START_ADDR_3_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_3_WM_PROT_START_ADDR_3_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_3 (0x830C0000 + 0x0C28)---

    WM_PROT_END_ADDR_3[31..0]    - (RW) Portect_3 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_3_WM_PROT_END_ADDR_3_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_3_WM_PROT_END_ADDR_3_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_3_WM_PROT_END_ADDR_3_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_4 (0x830C0000 + 0x0C2C)---

    WM_PROT_START_ADDR_4[31..0]  - (RW) Portect_4 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_4_WM_PROT_START_ADDR_4_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_4_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_4_WM_PROT_START_ADDR_4_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_4[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_4_WM_PROT_START_ADDR_4_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_4 (0x830C0000 + 0x0C30)---

    WM_PROT_END_ADDR_4[31..0]    - (RW) Portect_4 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_4_WM_PROT_END_ADDR_4_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_4_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_4_WM_PROT_END_ADDR_4_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_4[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_4_WM_PROT_END_ADDR_4_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_5 (0x830C0000 + 0x0C34)---

    WM_PROT_START_ADDR_5[31..0]  - (RW) Portect_5 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_5_WM_PROT_START_ADDR_5_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_5_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_5_WM_PROT_START_ADDR_5_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_5[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_5_WM_PROT_START_ADDR_5_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_5 (0x830C0000 + 0x0C38)---

    WM_PROT_END_ADDR_5[31..0]    - (RW) Portect_5 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_5_WM_PROT_END_ADDR_5_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_5_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_5_WM_PROT_END_ADDR_5_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_5[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_5_WM_PROT_END_ADDR_5_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_6 (0x830C0000 + 0x0C3C)---

    WM_PROT_START_ADDR_6[31..0]  - (RW) Portect_6 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_6_WM_PROT_START_ADDR_6_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_6_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_6_WM_PROT_START_ADDR_6_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_6[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_6_WM_PROT_START_ADDR_6_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_6 (0x830C0000 + 0x0C40)---

    WM_PROT_END_ADDR_6[31..0]    - (RW) Portect_6 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_6_WM_PROT_END_ADDR_6_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_6_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_6_WM_PROT_END_ADDR_6_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_6[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_6_WM_PROT_END_ADDR_6_SHFT 0

/* =====================================================================================

  ---WM_PROT_START_ADDR_7 (0x830C0000 + 0x0C44)---

    WM_PROT_START_ADDR_7[31..0]  - (RW) Portect_7 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_7_WM_PROT_START_ADDR_7_ADDR CONN_MCU_BUS_CR_WM_PROT_START_ADDR_7_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_7_WM_PROT_START_ADDR_7_MASK 0xFFFFFFFF                // WM_PROT_START_ADDR_7[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_START_ADDR_7_WM_PROT_START_ADDR_7_SHFT 0

/* =====================================================================================

  ---WM_PROT_END_ADDR_7 (0x830C0000 + 0x0C48)---

    WM_PROT_END_ADDR_7[31..0]    - (RW) Portect_7 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_7_WM_PROT_END_ADDR_7_ADDR CONN_MCU_BUS_CR_WM_PROT_END_ADDR_7_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_7_WM_PROT_END_ADDR_7_MASK 0xFFFFFFFF                // WM_PROT_END_ADDR_7[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_END_ADDR_7_WM_PROT_END_ADDR_7_SHFT 0

/* =====================================================================================

  ---WM_PROT_ADDR_FETCH_CLR (0x830C0000 + 0x0C4C)---

    WM_PROT_ADDR_FETCH_CLR[0]    - (RW) clear fetch address
                                     write 1 to clear address fetch, and you have to write 0 after clear address
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_ADDR_FETCH_CLR_WM_PROT_ADDR_FETCH_CLR_ADDR CONN_MCU_BUS_CR_WM_PROT_ADDR_FETCH_CLR_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_ADDR_FETCH_CLR_WM_PROT_ADDR_FETCH_CLR_MASK 0x00000001                // WM_PROT_ADDR_FETCH_CLR[0]
#define CONN_MCU_BUS_CR_WM_PROT_ADDR_FETCH_CLR_WM_PROT_ADDR_FETCH_CLR_SHFT 0

/* =====================================================================================

  ---WM_PROT_IRQ_ADDR_FETCH (0x830C0000 + 0x0C50)---

    WM_PROT_IRQ_ADDR_FETCH[31..0] - (RO) Irq address fetch

 =====================================================================================*/
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_ADDR_FETCH_WM_PROT_IRQ_ADDR_FETCH_ADDR CONN_MCU_BUS_CR_WM_PROT_IRQ_ADDR_FETCH_ADDR
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_ADDR_FETCH_WM_PROT_IRQ_ADDR_FETCH_MASK 0xFFFFFFFF                // WM_PROT_IRQ_ADDR_FETCH[31..0]
#define CONN_MCU_BUS_CR_WM_PROT_IRQ_ADDR_FETCH_WM_PROT_IRQ_ADDR_FETCH_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_EN (0x830C0000 + 0x0C60)---

    CMDBT_0_PROT_EN[0]           - (RW) wf_mcu_bus access portect en for cmdbt_0
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_EN_CMDBT_0_PROT_EN_ADDR   CONN_MCU_BUS_CR_CMDBT_0_PROT_EN_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_EN_CMDBT_0_PROT_EN_MASK   0x00000001                // CMDBT_0_PROT_EN[0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_EN_CMDBT_0_PROT_EN_SHFT   0

/* =====================================================================================

  ---CMDBT_0_PROT_IRQ_CLR (0x830C0000 + 0x0C64)---

    CMDBT_0_PROT_IRQ_CLR[0]      - (RW) wf_mcu_bus access portect irq clear for cmdbt_0
                                     write 1 to clear irq and after irq clr, you need to write 0
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_CLR_CMDBT_0_PROT_IRQ_CLR_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_CLR_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_CLR_CMDBT_0_PROT_IRQ_CLR_MASK 0x00000001                // CMDBT_0_PROT_IRQ_CLR[0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_CLR_CMDBT_0_PROT_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_WR_CTRL (0x830C0000 + 0x0C68)---

    CMDBT_0_PROT_WR_CTRL_0[1..0] - (RW) Portect_0_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_0_PROT_WR_CTRL_1[3..2] - (RW) Portect_1_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_0_PROT_WR_CTRL_2[5..4] - (RW) Portect_2_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_0_PROT_WR_CTRL_3[7..6] - (RW) Portect_3_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_3_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_3_MASK 0x000000C0                // CMDBT_0_PROT_WR_CTRL_3[7..6]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_3_SHFT 6
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_2_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_2_MASK 0x00000030                // CMDBT_0_PROT_WR_CTRL_2[5..4]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_2_SHFT 4
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_1_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_1_MASK 0x0000000C                // CMDBT_0_PROT_WR_CTRL_1[3..2]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_1_SHFT 2
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_0_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_0_MASK 0x00000003                // CMDBT_0_PROT_WR_CTRL_0[1..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_WR_CTRL_CMDBT_0_PROT_WR_CTRL_0_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_START_ADDR_0 (0x830C0000 + 0x0C6C)---

    CMDBT_0_PROT_START_ADDR_0[31..0] - (RW) Portect_0 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_0_CMDBT_0_PROT_START_ADDR_0_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_0_CMDBT_0_PROT_START_ADDR_0_MASK 0xFFFFFFFF                // CMDBT_0_PROT_START_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_0_CMDBT_0_PROT_START_ADDR_0_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_END_ADDR_0 (0x830C0000 + 0x0C70)---

    CMDBT_0_PROT_END_ADDR_0[31..0] - (RW) Portect_0 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_0_CMDBT_0_PROT_END_ADDR_0_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_0_CMDBT_0_PROT_END_ADDR_0_MASK 0xFFFFFFFF                // CMDBT_0_PROT_END_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_0_CMDBT_0_PROT_END_ADDR_0_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_START_ADDR_1 (0x830C0000 + 0x0C74)---

    CMDBT_0_PROT_START_ADDR_1[31..0] - (RW) Portect_1 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_1_CMDBT_0_PROT_START_ADDR_1_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_1_CMDBT_0_PROT_START_ADDR_1_MASK 0xFFFFFFFF                // CMDBT_0_PROT_START_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_1_CMDBT_0_PROT_START_ADDR_1_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_END_ADDR_1 (0x830C0000 + 0x0C78)---

    CMDBT_0_PROT_END_ADDR_1[31..0] - (RW) Portect_1 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_1_CMDBT_0_PROT_END_ADDR_1_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_1_CMDBT_0_PROT_END_ADDR_1_MASK 0xFFFFFFFF                // CMDBT_0_PROT_END_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_1_CMDBT_0_PROT_END_ADDR_1_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_START_ADDR_2 (0x830C0000 + 0x0C7C)---

    CMDBT_0_PROT_START_ADDR_2[31..0] - (RW) Portect_2 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_2_CMDBT_0_PROT_START_ADDR_2_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_2_CMDBT_0_PROT_START_ADDR_2_MASK 0xFFFFFFFF                // CMDBT_0_PROT_START_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_2_CMDBT_0_PROT_START_ADDR_2_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_END_ADDR_2 (0x830C0000 + 0x0C80)---

    CMDBT_0_PROT_END_ADDR_2[31..0] - (RW) Portect_2 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_2_CMDBT_0_PROT_END_ADDR_2_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_2_CMDBT_0_PROT_END_ADDR_2_MASK 0xFFFFFFFF                // CMDBT_0_PROT_END_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_2_CMDBT_0_PROT_END_ADDR_2_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_START_ADDR_3 (0x830C0000 + 0x0C84)---

    CMDBT_0_PROT_START_ADDR_3[31..0] - (RW) Portect_3 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_3_CMDBT_0_PROT_START_ADDR_3_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_3_CMDBT_0_PROT_START_ADDR_3_MASK 0xFFFFFFFF                // CMDBT_0_PROT_START_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_START_ADDR_3_CMDBT_0_PROT_START_ADDR_3_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_END_ADDR_3 (0x830C0000 + 0x0C88)---

    CMDBT_0_PROT_END_ADDR_3[31..0] - (RW) Portect_3 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_3_CMDBT_0_PROT_END_ADDR_3_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_3_CMDBT_0_PROT_END_ADDR_3_MASK 0xFFFFFFFF                // CMDBT_0_PROT_END_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_END_ADDR_3_CMDBT_0_PROT_END_ADDR_3_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_ADDR_FETCH_CLR (0x830C0000 + 0x0C8C)---

    CMDBT_0_PROT_ADDR_FETCH_CLR[0] - (RW) clear fetch address
                                     write 1 to clear address fetch, and you have to write 0 after clear address
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_ADDR_FETCH_CLR_CMDBT_0_PROT_ADDR_FETCH_CLR_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_ADDR_FETCH_CLR_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_ADDR_FETCH_CLR_CMDBT_0_PROT_ADDR_FETCH_CLR_MASK 0x00000001                // CMDBT_0_PROT_ADDR_FETCH_CLR[0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_ADDR_FETCH_CLR_CMDBT_0_PROT_ADDR_FETCH_CLR_SHFT 0

/* =====================================================================================

  ---CMDBT_0_PROT_IRQ_ADDR_FETCH (0x830C0000 + 0x0C90)---

    CMDBT_0_PROT_IRQ_ADDR_FETCH[31..0] - (RO) Irq address fetch

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_ADDR_FETCH_CMDBT_0_PROT_IRQ_ADDR_FETCH_ADDR CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_ADDR_FETCH_ADDR
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_ADDR_FETCH_CMDBT_0_PROT_IRQ_ADDR_FETCH_MASK 0xFFFFFFFF                // CMDBT_0_PROT_IRQ_ADDR_FETCH[31..0]
#define CONN_MCU_BUS_CR_CMDBT_0_PROT_IRQ_ADDR_FETCH_CMDBT_0_PROT_IRQ_ADDR_FETCH_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_EN (0x830C0000 + 0x0CA0)---

    CMDBT_1_PROT_EN[0]           - (RW) wf_mcu_bus access portect en for cmdbt_1
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_EN_CMDBT_1_PROT_EN_ADDR   CONN_MCU_BUS_CR_CMDBT_1_PROT_EN_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_EN_CMDBT_1_PROT_EN_MASK   0x00000001                // CMDBT_1_PROT_EN[0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_EN_CMDBT_1_PROT_EN_SHFT   0

/* =====================================================================================

  ---CMDBT_1_PROT_IRQ_CLR (0x830C0000 + 0x0CA4)---

    CMDBT_1_PROT_IRQ_CLR[0]      - (RW) wf_mcu_bus access portect irq clear for cmdbt_1
                                     write 1 to clear irq and after irq clr, you need to write 0
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_CLR_CMDBT_1_PROT_IRQ_CLR_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_CLR_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_CLR_CMDBT_1_PROT_IRQ_CLR_MASK 0x00000001                // CMDBT_1_PROT_IRQ_CLR[0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_CLR_CMDBT_1_PROT_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_WR_CTRL (0x830C0000 + 0x0CA8)---

    CMDBT_1_PROT_WR_CTRL_0[1..0] - (RW) Portect_0_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_1_PROT_WR_CTRL_1[3..2] - (RW) Portect_1_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_1_PROT_WR_CTRL_2[5..4] - (RW) Portect_2_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    CMDBT_1_PROT_WR_CTRL_3[7..6] - (RW) Portect_3_WR_control
                                     2'b00 : disable
                                     2'b10 : write portect
                                     2'b01 : read protect
                                     2'b11 : read & write protect
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_3_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_3_MASK 0x000000C0                // CMDBT_1_PROT_WR_CTRL_3[7..6]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_3_SHFT 6
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_2_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_2_MASK 0x00000030                // CMDBT_1_PROT_WR_CTRL_2[5..4]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_2_SHFT 4
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_1_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_1_MASK 0x0000000C                // CMDBT_1_PROT_WR_CTRL_1[3..2]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_1_SHFT 2
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_0_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_0_MASK 0x00000003                // CMDBT_1_PROT_WR_CTRL_0[1..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_WR_CTRL_CMDBT_1_PROT_WR_CTRL_0_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_START_ADDR_0 (0x830C0000 + 0x0CAC)---

    CMDBT_1_PROT_START_ADDR_0[31..0] - (RW) Portect_0 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_0_CMDBT_1_PROT_START_ADDR_0_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_0_CMDBT_1_PROT_START_ADDR_0_MASK 0xFFFFFFFF                // CMDBT_1_PROT_START_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_0_CMDBT_1_PROT_START_ADDR_0_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_END_ADDR_0 (0x830C0000 + 0x0CB0)---

    CMDBT_1_PROT_END_ADDR_0[31..0] - (RW) Portect_0 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_0_CMDBT_1_PROT_END_ADDR_0_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_0_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_0_CMDBT_1_PROT_END_ADDR_0_MASK 0xFFFFFFFF                // CMDBT_1_PROT_END_ADDR_0[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_0_CMDBT_1_PROT_END_ADDR_0_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_START_ADDR_1 (0x830C0000 + 0x0CB4)---

    CMDBT_1_PROT_START_ADDR_1[31..0] - (RW) Portect_1 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_1_CMDBT_1_PROT_START_ADDR_1_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_1_CMDBT_1_PROT_START_ADDR_1_MASK 0xFFFFFFFF                // CMDBT_1_PROT_START_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_1_CMDBT_1_PROT_START_ADDR_1_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_END_ADDR_1 (0x830C0000 + 0x0CB8)---

    CMDBT_1_PROT_END_ADDR_1[31..0] - (RW) Portect_1 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_1_CMDBT_1_PROT_END_ADDR_1_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_1_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_1_CMDBT_1_PROT_END_ADDR_1_MASK 0xFFFFFFFF                // CMDBT_1_PROT_END_ADDR_1[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_1_CMDBT_1_PROT_END_ADDR_1_SHFT 0

/* =====================================================================================

  ---MDBT_1_PROT_START_ADDR_2 (0x830C0000 + 0x0CBC)---

    CMDBT_1_PROT_START_ADDR_2[31..0] - (RW) Portect_2 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_MDBT_1_PROT_START_ADDR_2_CMDBT_1_PROT_START_ADDR_2_ADDR CONN_MCU_BUS_CR_MDBT_1_PROT_START_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_MDBT_1_PROT_START_ADDR_2_CMDBT_1_PROT_START_ADDR_2_MASK 0xFFFFFFFF                // CMDBT_1_PROT_START_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_MDBT_1_PROT_START_ADDR_2_CMDBT_1_PROT_START_ADDR_2_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_END_ADDR_2 (0x830C0000 + 0x0CC0)---

    CMDBT_1_PROT_END_ADDR_2[31..0] - (RW) Portect_2 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_2_CMDBT_1_PROT_END_ADDR_2_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_2_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_2_CMDBT_1_PROT_END_ADDR_2_MASK 0xFFFFFFFF                // CMDBT_1_PROT_END_ADDR_2[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_2_CMDBT_1_PROT_END_ADDR_2_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_START_ADDR_3 (0x830C0000 + 0x0CC4)---

    CMDBT_1_PROT_START_ADDR_3[31..0] - (RW) Portect_3 start address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_3_CMDBT_1_PROT_START_ADDR_3_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_3_CMDBT_1_PROT_START_ADDR_3_MASK 0xFFFFFFFF                // CMDBT_1_PROT_START_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_START_ADDR_3_CMDBT_1_PROT_START_ADDR_3_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_END_ADDR_3 (0x830C0000 + 0x0CC8)---

    CMDBT_1_PROT_END_ADDR_3[31..0] - (RW) Portect_3 end address

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_3_CMDBT_1_PROT_END_ADDR_3_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_3_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_3_CMDBT_1_PROT_END_ADDR_3_MASK 0xFFFFFFFF                // CMDBT_1_PROT_END_ADDR_3[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_END_ADDR_3_CMDBT_1_PROT_END_ADDR_3_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_ADDR_FETCH_CLR (0x830C0000 + 0x0CCC)---

    CMDBT_1_PROT_ADDR_FETCH_CLR[0] - (RW) clear fetch address
                                     write 1 to clear address fetch, and you have to write 0 after clear address
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_ADDR_FETCH_CLR_CMDBT_1_PROT_ADDR_FETCH_CLR_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_ADDR_FETCH_CLR_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_ADDR_FETCH_CLR_CMDBT_1_PROT_ADDR_FETCH_CLR_MASK 0x00000001                // CMDBT_1_PROT_ADDR_FETCH_CLR[0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_ADDR_FETCH_CLR_CMDBT_1_PROT_ADDR_FETCH_CLR_SHFT 0

/* =====================================================================================

  ---CMDBT_1_PROT_IRQ_ADDR_FETCH (0x830C0000 + 0x0CD0)---

    CMDBT_1_PROT_IRQ_ADDR_FETCH[31..0] - (RO) Irq address fetch

 =====================================================================================*/
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_ADDR_FETCH_CMDBT_1_PROT_IRQ_ADDR_FETCH_ADDR CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_ADDR_FETCH_ADDR
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_ADDR_FETCH_CMDBT_1_PROT_IRQ_ADDR_FETCH_MASK 0xFFFFFFFF                // CMDBT_1_PROT_IRQ_ADDR_FETCH[31..0]
#define CONN_MCU_BUS_CR_CMDBT_1_PROT_IRQ_ADDR_FETCH_CMDBT_1_PROT_IRQ_ADDR_FETCH_SHFT 0

/* =====================================================================================

  ---R_MCU_BUS_PROT_CG_EN (0x830C0000 + 0x0CE0)---

    R_MCU_BUS_PROT_CG_EN[0]      - (RW) CG_EN for  bus protect (default clock enable)
    R_MCU_BUS_PROT_RESERVE[31..1] - (RO) Reserve

 =====================================================================================*/
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_RESERVE_ADDR CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_ADDR
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_RESERVE_MASK 0xFFFFFFFE                // R_MCU_BUS_PROT_RESERVE[31..1]
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_RESERVE_SHFT 1
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_CG_EN_ADDR CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_ADDR
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_CG_EN_MASK 0x00000001                // R_MCU_BUS_PROT_CG_EN[0]
#define CONN_MCU_BUS_CR_R_MCU_BUS_PROT_CG_EN_R_MCU_BUS_PROT_CG_EN_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CONN_MCU_BUS_CR_REGS_H__
