#!/bin/sh

uci_write_config() {
	uci -q set cpufreq.cpufreq.governor$1="$2"
	uci -q set cpufreq.cpufreq.minfreq$1="$3"
	uci -q set cpufreq.cpufreq.maxfreq$1="$4"
	[ -n "$5" ] && uci -q set cpufreq.cpufreq.sdfactor$1="$5"
	[ -n "$6" ] && uci -q set cpufreq.cpufreq.upthreshold$1="$6"
	uci -q commit cpufreq
}

CPU_POLICYS="$(find '/sys/devices/system/cpu/cpufreq/policy'* -maxdepth 0 | grep -Eo '[0-9]+')"
source "/etc/openwrt_release"
case "$DISTRIB_TARGET" in
	"bcm27xx/bcm2710")
		uci_write_config 0 ondemand 600000 1200000 10 50
		;;
	"ipq40xx")
		uci_write_config 0 ondemand 300000 716000 10 50
		;;
	"ipq806x")
		uci_write_config 0 ondemand 600000 716000 10 50
		echo "$CPU_POLICYS" | grep -q "1" && uci_write_config 1 ondemand 600000 716000 10 50
		;;
	"rockchip/armv8")
		if echo "$CPU_POLICYS" | grep -q "4"; then
			uci_write_config 0 schedutil 600000 1608000
			uci_write_config 4 schedutil 600000 2016000
		else
			uci_write_config 0 schedutil 816000 1512000
		fi
		;;
esac

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cpufreq[-1]
	add ucitrack cpufreq
	set ucitrack.@cpufreq[-1].init=cpufreq
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
