#!/bin/sh

[ -f '/etc/rpcd_luci' ] && mv -f '/etc/rpcd_luci' '/usr/libexec/rpcd/luci'
[ -f '/etc/rpcd_luci-mod-status.json' ] && { mv -f '/etc/rpcd_luci-mod-status.json' '/usr/share/rpcd/acl.d/luci-mod-status.json'; /etc/init.d/rpcd restart; }
[ -f '/etc/rpcd_10_system.js' ] && mv -f '/etc/rpcd_10_system.js' '/www/luci-static/resources/view/status/include/10_system.js'
