#!/bin/sh

. /etc/openwrt_release

CPUINFO_PATH="/proc/cpuinfo"
CPUFREQ_PATH="/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq"

cpu_arch="$(cat "$CPUINFO_PATH" 2>/dev/null | awk -F ': ' '/model name/ {print $2}' | head -n1 || echo 'N/A')"

case "$DISTRIB_TARGET" in
"x86"/*)
	cpu_cores="$(cat "$CPUINFO_PATH" 2>/dev/null | awk -F ': ' '/cpu cores/ {print $2}' | head -n1)C $(grep -c "processor" "$CPUINFO_PATH")T"
	;;
*)
	cpu_cores="$(grep -c "processor" "$CPUINFO_PATH")"
	;;
esac

case "$DISTRIB_TARGET" in
"bcm27xx"/*)
	cpu_freq="$(( $(vcgencmd measure_clock arm | awk -F '=' '{print $2}') / 1000000 ))MHz"
	;;
"bcm53xx"/*)
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz"
	;;
"x86"/*)
	cpu_freq="$(cat "$CPUINFO_PATH" 2>/dev/null | awk -F ': ' '/cpu MHz/ {print $2}' | head -n1)MHz"
	;;
*)
	cpu_freq="$(cat "$CPUFREQ_PATH" 2>/dev/null | awk '{printf("%.1fMHz", $0 / 1000)}')"
	;;
esac

if [ -n "$cpu_freq" ]; then
	echo -n "$cpu_arch x $cpu_cores ($cpu_freq)"
else
	echo -n "$cpu_arch x $cpu_cores"
fi
