#!/bin/sh

. /etc/openwrt_release

IEEE_PATH="/sys/class/ieee80211"
THERMAL_PATH="/sys/class/thermal/thermal_zone0/temp"

case "$DISTRIB_TARGET" in
ipq40xx/*|ipq806x/*)
	wifi_temp="$(cat $IEEE_PATH/phy*/device/hwmon/hwmon*/temp1_input 2>/dev/null | awk '{printf("%.1f°C ", $0 / 1000)}')"
	mt76_temp="$(cat "$IEEE_PATH/phy0/hwmon0/temp1_input" 2>/dev/null | awk -F ': ' '{print $2}')°C"
	[ -n "$mt76_temp" ] && wifi_temp="${wifi_temp} ${mt76_temp}"
	;;
mediatek/mt7622)
	wifi_temp="$(cat $IEEE_PATH/wl*/hwmon*/temp1_input 2>/dev/null | awk '{printf("%.1f°C ", $0 / 1000)}')"
	;;
*)
	wifi_temp="$(cat $IEEE_PATH/phy*/hwmon*/temp1_input 2>/dev/null | awk '{printf("%.1f°C ", $0 / 1000)}')"
	;;
esac

case "$DISTRIB_TARGET" in
bcm27xx/*)
	cpu_temp="$(vcgencmd measure_temp | awk -F '=' '{print $2}' | awk -F "'" '{print $1}')°C"
	;;
x86/*)
	if [ -n "$(uci -q get "wechatpush.config.server_host")" ]; then
		cpu_temp="$(/usr/share/wechatpush/wechatpush soc)°C"
	elif grep -q "GenuineIntel" "/proc/cpuinfo"; then
		cpu_temp="$(sensors "coretemp-*" 2>/dev/null | grep -E "(Package id | Core)" | grep -Eo "\+[0-9.]*°C" | head -n1 | tr -d "+")"
	elif grep -q "AuthenticAMD" "/proc/cpuinfo"; then
		cpu_temp="$(sensors "k10temp-*" 2>/dev/null | awk '/Tctl|Tdie/ {print $2}' | head -n1 | tr -d "+")"
	fi
	;;
*)
	cpu_temp="$(cat "$THERMAL_PATH" 2>/dev/null | awk '{printf("%.1f°C", $0 / 1000)}')"
	;;
esac

if [ -n "$cpu_temp" ] && [ -z "$wifi_temp" ]; then
	echo -n "CPU: $cpu_temp"
elif [ -z "$cpu_temp" ] && [ -n "$wifi_temp" ]; then
	echo -n "WiFi: $wifi_temp"
elif [ -n "$cpu_temp" ] && [ -n "$wifi_temp" ]; then
	echo -n "CPU: $cpu_temp WiFi: $wifi_temp"
else
	echo -n "No temperature info"
fi
