#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@naiveproxy[-1]
	add ucitrack naiveproxy
	set ucitrack.@naiveproxy[-1].init=naiveproxy
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
