#!/bin/sh /etc/rc.common
#Author:KyleRicardo
#Email:shaoyz714@126.com

[ "$ACTION" = ifup ] || exit 0

iface=wan6

[ -z "$iface" -o "$INTERFACE" = "$iface" ] || exit 0

ip -6 route add `ip -6 route show default|sed -e 's/from [^ ]* //'`
logger -t IPv6 "Add IPv6 default route."

MAX_TRIES=99

WAN6_NAME="wan6"

WAN6_INTERFACE=$(uci get "network.$WAN6_NAME.ifname")
#eth0.2 by default

LAN_IP6PREFIX=$(uci get network.lan.ip6prefix)
#e.g. aaaa:bbbb:cccc:dddd::/64

#LAN_ULA_PREFIX=$(uci get network.globals.ula_prefix)
#e.g. ddc2:d512:65f5::/48

PROBE=0

COUNT=1

while [ $PROBE -eq 0 ]
do
	if [ $COUNT -gt $MAX_TRIES ];then
		logger -t NAT6 "No IPv6 route found (reached retry limit $MAX_TRIES times)" && exit 1
	fi
	sleep 5
	logger -t NAT6 "Probing IPv6 route ($COUNT time)"
	COUNT=$((COUNT+1))
	PROBE=$(route -A inet6 | grep -c '::/0')
done

#ip6tables -t nat -I POSTROUTING -s "$LAN_ULA_PREFIX" -o "$WAN6_INTERFACE" -j MASQUERADE
ip6tables -t nat -I POSTROUTING -s "$LAN_IP6PREFIX" -o "$WAN6_INTERFACE" -j MASQUERADE

#WAN6_GATEWAY=$(route -A inet6 -e | grep "$WAN6_INTERFACE" | awk '/::\/0/{print $2; exit}')
#get gateway from routing table. !!!Caution!!! May not work !
WAN6_GATEWAY=$(ifconfig eth0.2 | grep 'Global' | awk '{print $3}'| awk -F':' '{print $1":"$2":"$3":"$4"::1"}')
#caculate gateway from wan ipv6
#WAN6_GATEWAY=$(tracepath6 -n tv.byr.cn | grep ' 1: ' | awk 'NR==1 {print $2}')

#route -A inet6 add 2000::/3 gw "$WAN6_GATEWAY" dev "$WAN6_INTERFACE"
route -A inet6 add default gw "$WAN6_GATEWAY" dev "$WAN6_INTERFACE"

logger -t NAT6 "Done with IPv6 settings"
