include $(TOPDIR)/rules.mk

LUCI_TITLE:=MentoHUST 802.1X Client for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for 8021xclient.
LUCI_DEPENDS:=+mentohust
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-mentohust
PKG_VERSION:=1.1.1
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

