include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-mentohust
PKG_VERSION:=1.1.1
PKG_RELEASE:=0

LUCI_TITLE:=MentoHUST 802.1X Client for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for 8021xclient.
LUCI_DEPENDS:=+mentohust

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
