#!/bin/sh /etc/rc.common
# Created By [CTCGFW]Project OpenWRT
# https://github.com/project-openwrt

START=80
STOP=10

lan_addr="$(uci get network.lan.ipaddr)"

enable="$(uci get unblockneteasemusic-go.@unblockneteasemusic-go[0].enable)"
http_port="$(uci get unblockneteasemusic-go.@unblockneteasemusic-go[0].http_port)"
https_port="$(uci get unblockneteasemusic-go.@unblockneteasemusic-go[0].https_port)"
music_source="$(uci get unblockneteasemusic-go.@unblockneteasemusic-go[0].music_source)"
hijack_ways="$(uci get unblockneteasemusic-go.@unblockneteasemusic-go[0].hijack_ways)"

set_ipset(){
	if [ "${set_type}" = "start" ]; then
		mkdir -p "/tmp/dnsmasq.d"
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
ipset=/.music.163.com/musicgo
ipset=/interface.music.163.com/musicgo
ipset=/interface3.music.163.com/musicgo
ipset=/apm.music.163.com/musicgo
ipset=/apm3.music.163.com/musicgo
		EOF
		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1

		if ! ipset list musicgo > "/dev/null"; then ipset create musicgo hash:ip; fi
		curl -s "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' |sort |uniq |awk '{print "ipset add musicgo "$1}' |bash > "/dev/null" 2>&1
		iptables -t nat -N cloud_music_go
		iptables -t nat -A cloud_music_go -d 0.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music_go -d 10.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music_go -d 127.0.0.0/8 -j RETURN
		iptables -t nat -A cloud_music_go -d 169.254.0.0/16 -j RETURN
		iptables -t nat -A cloud_music_go -d 172.16.0.0/12 -j RETURN
		iptables -t nat -A cloud_music_go -d 192.168.0.0/16 -j RETURN
		iptables -t nat -A cloud_music_go -d 224.0.0.0/4 -j RETURN
		iptables -t nat -A cloud_music_go -d 240.0.0.0/4 -j RETURN
		iptables -t nat -A cloud_music_go -p tcp --dport 80 -j REDIRECT --to-ports "${http_port}"
		iptables -t nat -A cloud_music_go -p tcp --dport 443 -j REDIRECT --to-ports "${https_port}"
		iptables -t nat -I PREROUTING -p tcp -m set --match-set musicgo dst -j cloud_music_go

		mkdir -p /var/etc
		cat <<-EOF >> "/var/etc/unblockneteasemusic-go.include"
/etc/init.d/unblockneteasemusic-go restart
		EOF
	elif [ "${set_type}" = "stop" ]; then
		iptables -t nat -D PREROUTING -p tcp -m set --match-set musicgo dst -j cloud_music_go
		iptables -t nat -F cloud_music_go
		iptables -t nat -X cloud_music_go
		ipset destroy musicgo

		echo "" > "/var/etc/unblockneteasemusic-go.include"
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1
	fi
}

set_hosts(){
	if [ "${set_type}" = "start" ]; then
		mkdir -p "/tmp/dnsmasq.d"
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
address=/music.163.com/${lan_addr}
address=/interface.music.163.com/${lan_addr}
address=/interface3.music.163.com/${lan_addr}
address=/apm.music.163.com/${lan_addr}
address=/apm3.music.163.com/${lan_addr}
address=/music.httpdns.c.163.com/0.0.0.0
		EOF
		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1

		ip route add 223.252.199.10 dev lo
	elif [ "${set_type}" = "stop" ]; then
		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic-go.conf"
		/etc/init.d/dnsmasq reload > "/dev/null" 2>&1

		ip route del 223.252.199.10
	fi
}

start()
{
	stop

	[ "${enable}" -ne "1" ] && exit 0
	if [ "${music_source}" = "default" ]; then
		nohup UnblockNeteaseMusic -p "${http_port}" -sp "${https_port}" -m "0" -c "/usr/share/UnblockNeteaseMusic-Go/server.crt" -k "/usr/share/UnblockNeteaseMusic-Go/server.key" > "/tmp/unblockneteasemusic-go.log" 2>&1 &
	else
		nohup UnblockNeteaseMusic -p "${http_port}" -sp "${https_port}" -o "${music_source}" -m "0" -c "/usr/share/UnblockNeteaseMusic-Go/server.crt" -k "/usr/share/UnblockNeteaseMusic-Go/server.key" > "/tmp/unblockneteasemusic-go.log" 2>&1 &
	fi

	set_type="start"
	if [ "${hijack_ways}" = "use_ipset" ]; then
		set_ipset > "/dev/null" 2>&1
	elif [ "${hijack_ways}" = "use_hosts" ]; then
		set_hosts > "/dev/null" 2>&1
	fi

	sed -i '/UnblockNeteaseMusic-Go/d' /etc/crontabs/root
	echo "*/5 * * * * /usr/share/UnblockNeteaseMusic-Go/log_check.sh" >> "/etc/crontabs/root"
	/etc/init.d/cron restart > "/dev/null" 2>&1
}

stop()
{
	killall -9 "UnblockNeteaseMusic" > "/dev/null" 2>&1

	sed -i '/UnblockNeteaseMusic-Go/d' "/etc/crontabs/root"
	/etc/init.d/cron restart > "/dev/null" 2>&1

	rm -f "/tmp/unblockneteasemusic-go.log"

	set_type="stop"
	set_ipset > "/dev/null" 2>&1
	set_hosts > "/dev/null" 2>&1
}
