include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-minieap
PKG_VERSION=1.0.2
PKG_RELEASE:=0

LUCI_TITLE:=minieap 802.1X Client for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for 8021xclient.
LUCI_DEPENDS:=+minieap

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
