#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"
uci -q get system.@imm_init[0].ipv6 > "/dev/null" && exit 0

uci -q batch <<-EOF
	set dhcp.lan.ra="hybrid"
	set dhcp.lan.ndp="hybrid"
	set dhcp.lan.dhcpv6="hybrid"
	set dhcp.lan.ra_management="1"
	commit dhcp

	set system.@imm_init[0].ipv6="1"
	commit system
EOF

exit 0
